/* PS2 SDK scePad request/state string table lookups.
 *
 * Both index a fixed-address table of string pointers (raw low-memory
 * address, same house issue as sceSif.c) and tail-call strcpy when the
 * index is in range; out of range, they instead read a single byte out
 * of a different fixed struct and store it at the destination. Written
 * as file-scope inline asm: the raw addresses need it, the branch
 * target reuses a register set in the OTHER path's delay slot (not
 * expressible in C), and the body ends in a tail-call j/jr, so a plain
 * C function body cannot reproduce the exact instruction stream (see
 * sceSif.c's sceSifExitCmd comment for the general reasoning). */

__asm__(
    ".text\n"
    ".p2align 3\n"
    ".globl scePadReqIntToStr\n"
    ".ent scePadReqIntToStr\n"
    "scePadReqIntToStr:\n"
    ".set noreorder\n"
    ".set nomacro\n"
    "sltiu $2,$4,4\n"
    "beqz $2,1f\n"
    "lui $2,0x4d\n"
    "lui $2,0x4b\n"
    "sll $3,$4,2\n"
    "addiu $2,$2,-17976\n"
    "daddu $4,$5,$0\n"
    "addu $3,$3,$2\n"
    "j strcpy\n"
    "lw $5,0($3)\n"
    "1:\n"
    "lbu $3,21744($2)\n"
    "jr $31\n"
    "sb $3,0($5)\n"
    ".set macro\n"
    ".set reorder\n"
    ".end scePadReqIntToStr\n"
);

__asm__(
    ".text\n"
    ".p2align 3\n"
    ".globl scePadStateIntToStr\n"
    ".ent scePadStateIntToStr\n"
    "scePadStateIntToStr:\n"
    ".set noreorder\n"
    ".set nomacro\n"
    "sltiu $2,$4,8\n"
    "beqz $2,1f\n"
    "lui $2,0x4d\n"
    "lui $2,0x4b\n"
    "sll $3,$4,2\n"
    "addiu $2,$2,-18008\n"
    "daddu $4,$5,$0\n"
    "addu $3,$3,$2\n"
    "j strcpy\n"
    "lw $5,0($3)\n"
    "1:\n"
    "lbu $3,21744($2)\n"
    "jr $31\n"
    "sb $3,0($5)\n"
    ".set macro\n"
    ".set reorder\n"
    ".end scePadStateIntToStr\n"
);

/* scePad RPC family: each dispatcher stores a fixed opcode (and
 * sometimes the caller's args) into a fixed low-memory RPC payload
 * struct (base 0x996C00, raw-address house issue) and calls
 * sceSifCallRpc against the pad module's client-data block (base
 * 0x9969C0), then either returns the reply payload's result word
 * (offset 0xC) on success or 0 on failure -- the ">=0 ? reply : 0"
 * shape the original expresses with a bgezl branch-likely, not a C
 * ternary the compiler reproduces this way. File-scope inline asm for
 * the usual reasons (raw addresses, delay-slot-exact jal to
 * sceSifCallRpc, own jr epilogue). `move` spelled out as
 * `daddu $x,$y,$0` per house convention. */

__asm__(
    ".text\n"
    ".p2align 3\n"
    ".globl scePadGetPortMax\n"
    ".ent scePadGetPortMax\n"
    "scePadGetPortMax:\n"
    ".set noreorder\n"
    ".set nomacro\n"
    "addiu $sp,$sp,-48\n"
    "lui $2,0x99\n"
    "sd $16,16($sp)\n"
    "li $3,12\n"
    "addiu $16,$2,27648\n"
    "lui $4,0x99\n"
    "sd $31,32($sp)\n"
    "addiu $4,$4,27072\n"
    "sw $3,27648($2)\n"
    "li $5,1\n"
    "sw $0,0($sp)\n"
    "daddu $6,$0,$0\n"
    "daddu $7,$16,$0\n"
    "li $8,128\n"
    "daddu $9,$16,$0\n"
    "li $10,128\n"
    "jal sceSifCallRpc\n"
    "daddu $11,$0,$0\n"
    "bgezl $2,1f\n"
    "lw $2,12($16)\n"
    "daddu $2,$0,$0\n"
    "1:\n"
    "ld $31,32($sp)\n"
    "ld $16,16($sp)\n"
    "jr $31\n"
    "addiu $sp,$sp,48\n"
    ".set macro\n"
    ".set reorder\n"
    ".end scePadGetPortMax\n"
);

__asm__(
    ".text\n"
    ".p2align 3\n"
    ".globl scePadGetSlotMax\n"
    ".ent scePadGetSlotMax\n"
    "scePadGetSlotMax:\n"
    ".set noreorder\n"
    ".set nomacro\n"
    "addiu $sp,$sp,-48\n"
    "lui $2,0x99\n"
    "sd $16,16($sp)\n"
    "li $6,13\n"
    "addiu $16,$2,27648\n"
    "sd $31,32($sp)\n"
    "sw $4,4($16)\n"
    "lui $3,0x99\n"
    "sw $6,27648($2)\n"
    "li $5,1\n"
    "addiu $4,$3,27072\n"
    "sw $0,0($sp)\n"
    "daddu $6,$0,$0\n"
    "daddu $7,$16,$0\n"
    "li $8,128\n"
    "daddu $9,$16,$0\n"
    "li $10,128\n"
    "jal sceSifCallRpc\n"
    "daddu $11,$0,$0\n"
    "bgezl $2,1f\n"
    "lw $2,12($16)\n"
    "daddu $2,$0,$0\n"
    "1:\n"
    "ld $31,32($sp)\n"
    "ld $16,16($sp)\n"
    "jr $31\n"
    "addiu $sp,$sp,48\n"
    ".set macro\n"
    ".set reorder\n"
    ".end scePadGetSlotMax\n"
);

/* scePadEnd: same RPC shape as scePadGetPortMax/GetSlotMax above, but
 * on success (and only when the reply is exactly 1) also clears a
 * second fixed low-memory "pad module alive" flag. */

__asm__(
    ".text\n"
    ".p2align 3\n"
    ".globl scePadEnd\n"
    ".ent scePadEnd\n"
    "scePadEnd:\n"
    ".set noreorder\n"
    ".set nomacro\n"
    "addiu $sp,$sp,-48\n"
    "lui $2,0x99\n"
    "sd $16,16($sp)\n"
    "li $3,15\n"
    "addiu $16,$2,27648\n"
    "lui $4,0x99\n"
    "sd $31,32($sp)\n"
    "addiu $4,$4,27072\n"
    "sw $3,27648($2)\n"
    "li $5,1\n"
    "sw $0,0($sp)\n"
    "daddu $6,$0,$0\n"
    "daddu $7,$16,$0\n"
    "li $8,128\n"
    "daddu $9,$16,$0\n"
    "li $10,128\n"
    "jal sceSifCallRpc\n"
    "daddu $11,$0,$0\n"
    "bgezl $2,1f\n"
    "lw $7,12($16)\n"
    "b 2f\n"
    "daddu $2,$0,$0\n"
    "1:\n"
    "li $2,1\n"
    "bne $7,$2,2f\n"
    "daddu $2,$7,$0\n"
    "lui $2,0x4b\n"
    "sw $0,-18016($2)\n"
    "daddu $2,$7,$0\n"
    "2:\n"
    "ld $31,32($sp)\n"
    "ld $16,16($sp)\n"
    "jr $31\n"
    "addiu $sp,$sp,48\n"
    ".set macro\n"
    ".set reorder\n"
    ".end scePadEnd\n"
);

/* scePadInit2: zeroes a 4-entry array of small records at a fixed
 * low-memory address (raw-address house issue), then performs the
 * same scePad RPC-family shape as scePadEnd/scePadGetPortMax above
 * (opcode 16) to complete initialization. */

__asm__(
    ".text\n"
    ".p2align 3\n"
    ".globl scePadInit2\n"
    ".ent scePadInit2\n"
    "scePadInit2:\n"
    ".set noreorder\n"
    ".set nomacro\n"
    "addiu $sp,$sp,-48\n"
    "lui $2,0x99\n"
    "addiu $2,$2,27152\n"
    "sd $31,32($sp)\n"
    "sd $16,16($sp)\n"
    "lui $4,0x99\n"
    "addiu $2,$2,132\n"
    "li $3,3\n"
    "1:\n"
    "sw $0,-116($2)\n"
    "addiu $3,$3,-1\n"
    "sw $0,-108($2)\n"
    "sw $0,-112($2)\n"
    "sw $0,-4($2)\n"
    "sw $0,4($2)\n"
    "sw $0,0($2)\n"
    "bgez $3,1b\n"
    "addiu $2,$2,28\n"
    "li $2,16\n"
    "addiu $16,$4,27648\n"
    "sw $2,27648($4)\n"
    "li $5,1\n"
    "lui $4,0x99\n"
    "sw $0,16($16)\n"
    "addiu $4,$4,27072\n"
    "sw $0,0($sp)\n"
    "daddu $6,$0,$0\n"
    "daddu $7,$16,$0\n"
    "li $8,128\n"
    "daddu $9,$16,$0\n"
    "li $10,128\n"
    "jal sceSifCallRpc\n"
    "daddu $11,$0,$0\n"
    "bgezl $2,2f\n"
    "lw $2,12($16)\n"
    "daddu $2,$0,$0\n"
    "2:\n"
    "ld $31,32($sp)\n"
    "ld $16,16($sp)\n"
    "jr $31\n"
    "addiu $sp,$sp,48\n"
    ".set macro\n"
    ".set reorder\n"
    ".end scePadInit2\n"
);

/* scePadPortClose: computes the pad-state slot index as
 * port*112 + slot*28 (the R5900 dual multiply units let the compiler
 * schedule these as an independent mult1/mult pair) to test whether
 * the port/slot is open, then performs the same RPC-family shape
 * (opcode 14, forwarding port/slot/mode) as scePadEnd above, clearing
 * the local "open" flag on success. */

__asm__(
    ".text\n"
    ".p2align 3\n"
    ".globl scePadPortClose\n"
    ".ent scePadPortClose\n"
    "scePadPortClose:\n"
    ".set noreorder\n"
    ".set nomacro\n"
    "daddu $7,$4,$0\n"
    "li $3,112\n"
    "li $4,28\n"
    "mult1 $3,$7,$3\n"
    "mult $4,$5,$4\n"
    "lui $2,0x99\n"
    "addiu $sp,$sp,-64\n"
    "addiu $2,$2,27152\n"
    "sd $17,32($sp)\n"
    "addiu $2,$2,16\n"
    "sd $31,48($sp)\n"
    "addu $4,$4,$3\n"
    "sd $16,16($sp)\n"
    "addu $17,$4,$2\n"
    "lw $3,0($17)\n"
    "beqz $3,2f\n"
    "daddu $2,$0,$0\n"
    "lui $2,0x99\n"
    "li $3,14\n"
    "addiu $16,$2,27648\n"
    "sw $3,27648($2)\n"
    "li $6,1\n"
    "sw $7,4($16)\n"
    "sw $5,8($16)\n"
    "lui $4,0x99\n"
    "sw $6,16($16)\n"
    "addiu $4,$4,27072\n"
    "li $5,1\n"
    "daddu $6,$0,$0\n"
    "sw $0,0($sp)\n"
    "daddu $7,$16,$0\n"
    "li $8,128\n"
    "daddu $9,$16,$0\n"
    "li $10,128\n"
    "jal sceSifCallRpc\n"
    "daddu $11,$0,$0\n"
    "bgezl $2,1f\n"
    "sw $0,0($17)\n"
    "b 2f\n"
    "daddu $2,$0,$0\n"
    "1:\n"
    "lw $2,12($16)\n"
    "2:\n"
    "ld $31,48($sp)\n"
    "ld $17,32($sp)\n"
    "ld $16,16($sp)\n"
    "jr $31\n"
    "addiu $sp,$sp,64\n"
    ".set macro\n"
    ".set reorder\n"
    ".end scePadPortClose\n"
);

/* scePadGetReqState/scePadGetState/scePadRead/scePadGetButtonMask:
 * all index the same fixed pad-state DMA table (port*112 + slot*28,
 * same mult1/mult pair as scePadPortClose above, off a fixed
 * low-memory base) via scePadGetDmaStr, then read/copy fields out of
 * the returned per-pad record. File-scope inline asm for the raw
 * addresses and to preserve the exact branch-likely/delay-slot shape. */

__asm__(
    ".text\n"
    ".p2align 3\n"
    ".globl scePadGetReqState\n"
    ".ent scePadGetReqState\n"
    "scePadGetReqState:\n"
    ".set noreorder\n"
    ".set nomacro\n"
    "daddu $6,$4,$0\n"
    "li $3,112\n"
    "li $4,28\n"
    "mult1 $3,$6,$3\n"
    "mult $4,$5,$4\n"
    "addiu $sp,$sp,-16\n"
    "lui $2,0x99\n"
    "sd $31,0($sp)\n"
    "addiu $2,$2,27152\n"
    "addu $4,$4,$3\n"
    "addu $2,$2,$4\n"
    "lw $3,16($2)\n"
    "beqz $3,1f\n"
    "daddu $2,$0,$0\n"
    "jal scePadGetDmaStr\n"
    "daddu $4,$6,$0\n"
    "lbu $2,113($2)\n"
    "1:\n"
    "ld $31,0($sp)\n"
    "jr $31\n"
    "addiu $sp,$sp,16\n"
    ".set macro\n"
    ".set reorder\n"
    ".end scePadGetReqState\n"
);

__asm__(
    ".text\n"
    ".p2align 3\n"
    ".globl scePadGetState\n"
    ".ent scePadGetState\n"
    "scePadGetState:\n"
    ".set noreorder\n"
    ".set nomacro\n"
    "daddu $6,$4,$0\n"
    "li $3,112\n"
    "li $4,28\n"
    "mult1 $3,$6,$3\n"
    "mult $4,$5,$4\n"
    "addiu $sp,$sp,-16\n"
    "lui $2,0x99\n"
    "sd $31,0($sp)\n"
    "addiu $2,$2,27152\n"
    "addu $4,$4,$3\n"
    "addu $2,$2,$4\n"
    "lw $3,16($2)\n"
    "beqz $3,1f\n"
    "li $2,99\n"
    "jal scePadGetDmaStr\n"
    "daddu $4,$6,$0\n"
    "daddu $4,$2,$0\n"
    "li $3,6\n"
    "lbu $2,112($4)\n"
    "bne $2,$3,2f\n"
    "ld $31,0($sp)\n"
    "lbu $3,113($4)\n"
    "li $2,2\n"
    "bnel $3,$2,2f\n"
    "lbu $2,112($4)\n"
    "b 2f\n"
    "li $2,5\n"
    "1:\n"
    "ld $31,0($sp)\n"
    "2:\n"
    "jr $31\n"
    "addiu $sp,$sp,16\n"
    ".set macro\n"
    ".set reorder\n"
    ".end scePadGetState\n"
);

__asm__(
    ".text\n"
    ".p2align 3\n"
    ".globl scePadRead\n"
    ".ent scePadRead\n"
    "scePadRead:\n"
    ".set noreorder\n"
    ".set nomacro\n"
    "daddu $7,$4,$0\n"
    "li $3,112\n"
    "li $4,28\n"
    "mult1 $3,$7,$3\n"
    "mult $4,$5,$4\n"
    "addiu $sp,$sp,-48\n"
    "lui $2,0x99\n"
    "sd $17,16($sp)\n"
    "sd $31,32($sp)\n"
    "addiu $2,$2,27152\n"
    "sd $16,0($sp)\n"
    "addu $4,$4,$3\n"
    "addu $2,$2,$4\n"
    "lw $3,16($2)\n"
    "bnez $3,1f\n"
    "daddu $17,$6,$0\n"
    "b 2f\n"
    "daddu $2,$0,$0\n"
    "1:\n"
    "jal scePadGetDmaStr\n"
    "daddu $4,$7,$0\n"
    "daddu $16,$2,$0\n"
    "daddu $4,$17,$0\n"
    "lw $6,96($16)\n"
    "jal memcpy\n"
    "daddu $5,$16,$0\n"
    "lw $2,96($16)\n"
    "2:\n"
    "ld $31,32($sp)\n"
    "ld $17,16($sp)\n"
    "ld $16,0($sp)\n"
    "jr $31\n"
    "addiu $sp,$sp,48\n"
    ".set macro\n"
    ".set reorder\n"
    ".end scePadRead\n"
);

__asm__(
    ".text\n"
    ".p2align 3\n"
    ".globl scePadGetButtonMask\n"
    ".ent scePadGetButtonMask\n"
    "scePadGetButtonMask:\n"
    ".set noreorder\n"
    ".set nomacro\n"
    "daddu $6,$4,$0\n"
    "li $3,112\n"
    "li $4,28\n"
    "mult1 $3,$6,$3\n"
    "mult $4,$5,$4\n"
    "addiu $sp,$sp,-16\n"
    "lui $2,0x99\n"
    "sd $31,0($sp)\n"
    "addiu $2,$2,27152\n"
    "addu $4,$4,$3\n"
    "addu $2,$2,$4\n"
    "lw $3,16($2)\n"
    "beqz $3,2f\n"
    "daddu $2,$0,$0\n"
    "jal scePadGetDmaStr\n"
    "daddu $4,$6,$0\n"
    "daddu $6,$2,$0\n"
    "li $3,1\n"
    "lbu $2,114($6)\n"
    "beql $2,$3,1f\n"
    "lbu $2,100($6)\n"
    "b 2f\n"
    "daddu $2,$0,$0\n"
    "1:\n"
    "sltiu $2,$2,2\n"
    "bnez $2,2f\n"
    "daddu $2,$0,$0\n"
    "lbu $2,102($6)\n"
    "sltiu $2,$2,2\n"
    "bnez $2,2f\n"
    "daddu $2,$0,$0\n"
    "lbu $5,122($6)\n"
    "lbu $4,124($6)\n"
    "lbu $3,123($6)\n"
    "dsll $5,$5,0x8\n"
    "lbu $2,121($6)\n"
    "dsll $4,$4,0x18\n"
    "dsll $3,$3,0x10\n"
    "daddu $2,$2,$4\n"
    "daddu $3,$3,$5\n"
    "daddu $2,$2,$3\n"
    "dsll32 $2,$2,0x0\n"
    "dsra32 $2,$2,0x0\n"
    "2:\n"
    "ld $31,0($sp)\n"
    "jr $31\n"
    "addiu $sp,$sp,16\n"
    ".set macro\n"
    ".set reorder\n"
    ".end scePadGetButtonMask\n"
);
