.include "macro.inc"

.section .bss, "wa"

/* Generated by spimdisasm 1.40.0 */

nonmatching _args, 0x150

dlabel _args
    /* 004DC880 */ .space 0x150

nonmatching CfCameraOfsNow, 0x10

dlabel CfCameraOfsNow
    /* 004DC9D0 */ .space 0x10

nonmatching CamPlayer, 0x40

dlabel CamPlayer
    /* 004DC9E0 */ .space 0x40

nonmatching CamPlyPosOld, 0x10

dlabel CamPlyPosOld
    /* 004DCA20 */ .space 0x10

nonmatching CamLookAt, 0x40

dlabel CamLookAt
    /* 004DCA30 */ .space 0x40

nonmatching CamLookAtPos, 0x10

dlabel CamLookAtPos
    /* 004DCA70 */ .space 0x10

nonmatching CamPos, 0x40

dlabel CamPos
    /* 004DCA80 */ .space 0x40

nonmatching CamPosPos, 0x10

dlabel CamPosPos
    /* 004DCAC0 */ .space 0x10

nonmatching HokanNow, 0x30

dlabel HokanNow
    /* 004DCAD0 */ .space 0x30

nonmatching EnemySeBank, 0x4

dlabel EnemySeBank
    /* 004DCB00 */ .space 0x04

nonmatching D_004DCB04, 0x9C

dlabel D_004DCB04
    /* 004DCB04 */ .space 0x9C

nonmatching foot_name, 0x10

dlabel foot_name
    /* 004DCBA0 */ .space 0x10

nonmatching env_name, 0x10

dlabel env_name
    /* 004DCBB0 */ .space 0x10

nonmatching scene_txt_buffer, 0x800

dlabel scene_txt_buffer
    /* 004DCBC0 */ .space 0x800

nonmatching archeader, 0x100

dlabel archeader
    /* 004DD3C0 */ .space 0x100

nonmatching GameResourceWorkReloadTable, 0x80

dlabel GameResourceWorkReloadTable
    /* 004DD4C0 */ .space 0x80

nonmatching mi, 0xD0

dlabel mi
    /* 004DD540 */ .space 0xD0

nonmatching outpath, 0x100

dlabel outpath
    /* 004DD610 */ .space 0x100

nonmatching tcomponent, 0x16C0

dlabel tcomponent
    /* 004DD710 */ .space 0x16C0

nonmatching evtDebug, 0x4

dlabel evtDebug
    /* 004DEDD0 */ .space 0x04

nonmatching D_004DEDD4, 0xC

dlabel D_004DEDD4
    /* 004DEDD4 */ .space 0x0C

nonmatching scriptDB, 0x8

dlabel scriptDB
    /* 004DEDE0 */ .space 0x08

nonmatching D_004DEDE8, 0x8

dlabel D_004DEDE8
    /* 004DEDE8 */ .space 0x08

nonmatching D_004DEDF0, 0x28

dlabel D_004DEDF0
    /* 004DEDF0 */ .space 0x28

nonmatching lightActFlags, 0x10

dlabel lightActFlags
    /* 004DEE18 */ .space 0x10

nonmatching heapInfo, 0x88

dlabel heapInfo
    /* 004DEE28 */ .space 0x88

nonmatching dbgWind, 0x30

dlabel dbgWind
    /* 004DEEB0 */ .space 0x30

nonmatching keyData, 0x10

dlabel keyData
    /* 004DEEE0 */ .space 0x10

nonmatching defaultStage, 0x30

dlabel defaultStage
    /* 004DEEF0 */ .space 0x30

nonmatching line00.3, 0xE0

dlabel line00.3
    /* 004DEF20 */ .space 0xE0

nonmatching line01.4, 0xE0

dlabel line01.4
    /* 004DF000 */ .space 0xE0

nonmatching line02.5, 0xE0

dlabel line02.5
    /* 004DF0E0 */ .space 0xE0

nonmatching line03.6, 0xE0

dlabel line03.6
    /* 004DF1C0 */ .space 0xE0

nonmatching line10.7, 0xE0

dlabel line10.7
    /* 004DF2A0 */ .space 0xE0

nonmatching line11.8, 0xE0

dlabel line11.8
    /* 004DF380 */ .space 0xE0

nonmatching line12.9, 0xE0

dlabel line12.9
    /* 004DF460 */ .space 0xE0

nonmatching msg.11, 0x50

dlabel msg.11
    /* 004DF540 */ .space 0x50

nonmatching bsp.12, 0x50

dlabel bsp.12
    /* 004DF590 */ .space 0x50

nonmatching rbn.21, 0x1C0

dlabel rbn.21
    /* 004DF5E0 */ .space 0x1C0

nonmatching spr.22, 0xA0

dlabel spr.22
    /* 004DF7A0 */ .space 0xA0

nonmatching line.23, 0x2C0

dlabel line.23
    /* 004DF840 */ .space 0x2C0

nonmatching tgf.24, 0x70

dlabel tgf.24
    /* 004DFB00 */ .space 0x70

nonmatching D_004DFB70, 0x10

dlabel D_004DFB70
    /* 004DFB70 */ .space 0x10

nonmatching cur.25, 0x50

dlabel cur.25
    /* 004DFB80 */ .space 0x50

nonmatching d.28, 0x60

dlabel d.28
    /* 004DFBD0 */ .space 0x60

nonmatching num.29, 0x90

dlabel num.29
    /* 004DFC30 */ .space 0x90

nonmatching num.30, 0x90

dlabel num.30
    /* 004DFCC0 */ .space 0x90

nonmatching num.31, 0x90

dlabel num.31
    /* 004DFD50 */ .space 0x90

nonmatching num.32, 0x90

dlabel num.32
    /* 004DFDE0 */ .space 0x90

nonmatching d.33, 0x18

dlabel d.33
    /* 004DFE70 */ .space 0x18

nonmatching d.35, 0x14

dlabel d.35
    /* 004DFE88 */ .space 0x14

nonmatching D_004DFE9C, 0x14

dlabel D_004DFE9C
    /* 004DFE9C */ .space 0x14

nonmatching d.36, 0x18

dlabel d.36
    /* 004DFEB0 */ .space 0x18

nonmatching d.38, 0x18

dlabel d.38
    /* 004DFEC8 */ .space 0x18

nonmatching d.39, 0x18

dlabel d.39
    /* 004DFEE0 */ .space 0x18

nonmatching d.40, 0x18

dlabel d.40
    /* 004DFEF8 */ .space 0x18

nonmatching d.41, 0x18

dlabel d.41
    /* 004DFF10 */ .space 0x18

nonmatching d.44, 0x38

dlabel d.44
    /* 004DFF28 */ .space 0x38

nonmatching fname.67, 0x40

dlabel fname.67
    /* 004DFF60 */ .space 0x40

nonmatching mm.73, 0x160

dlabel mm.73
    /* 004DFFA0 */ .space 0x160

nonmatching Menu02Tex, 0x604E

dlabel Menu02Tex
    /* 004E0100 */ .space 0x604E

nonmatching D_004E614E, 0x9FFA

dlabel D_004E614E
    /* 004E614E */ .space 0x9FFA

nonmatching D_004F0148, 0xFF58

dlabel D_004F0148
    /* 004F0148 */ .space 0xFF58

nonmatching D_005000A0, 0x10

dlabel D_005000A0
    /* 005000A0 */ .space 0x10

nonmatching D_005000B0, 0x2F73

dlabel D_005000B0
    /* 005000B0 */ .space 0x2F73

nonmatching D_00503023, 0x112A

dlabel D_00503023
    /* 00503023 */ .space 0x112A

nonmatching D_0050414D, 0x11FC

dlabel D_0050414D
    /* 0050414D */ .space 0x11FC

nonmatching D_00505349, 0x2CD8

dlabel D_00505349
    /* 00505349 */ .space 0x2CD8

nonmatching D_00508021, 0x812B

dlabel D_00508021
    /* 00508021 */ .space 0x812B

nonmatching D_0051014C, 0xED5

dlabel D_0051014C
    /* 0051014C */ .space 0xED5

nonmatching D_00511021, 0x800

dlabel D_00511021
    /* 00511021 */ .space 0x800

nonmatching D_00511821, 0x39CD

dlabel D_00511821
    /* 00511821 */ .space 0x39CD

nonmatching D_005151EE, 0xAE5E

dlabel D_005151EE
    /* 005151EE */ .space 0xAE5E

nonmatching D_0052004C, 0x8B4

dlabel D_0052004C
    /* 0052004C */ .space 0x8B4

nonmatching MenuWorkEndTop, 0x3F43

dlabel MenuWorkEndTop
    /* 00520900 */ .space 0x3F43

nonmatching D_00524843, 0x711

dlabel D_00524843
    /* 00524843 */ .space 0x711

nonmatching D_00524F54, 0x4FF

dlabel D_00524F54
    /* 00524F54 */ .space 0x4FF

nonmatching D_00525453, 0xACFE

dlabel D_00525453
    /* 00525453 */ .space 0xACFE

nonmatching D_00530151, 0x7AF

dlabel D_00530151
    /* 00530151 */ .space 0x7AF

nonmatching moji, 0xF18

dlabel moji
    /* 00530900 */ .space 0xF18

nonmatching D_00531818, 0xE8

dlabel D_00531818
    /* 00531818 */ .space 0xE8

nonmatching msg_spr, 0x140

dlabel msg_spr
    /* 00531900 */ .space 0x140

nonmatching PrintFunc, 0xFF8

dlabel PrintFunc
    /* 00531A40 */ .space 0xFF8

nonmatching D_00532A38, 0x8

dlabel D_00532A38
    /* 00532A38 */ .space 0x08

nonmatching gauge, 0x18

dlabel gauge
    /* 00532A40 */ .space 0x18

nonmatching MenuItemParty, 0x10

dlabel MenuItemParty
    /* 00532A58 */ .space 0x10

nonmatching MenuItemAgws, 0x10

dlabel MenuItemAgws
    /* 00532A68 */ .space 0x10

nonmatching msg.2_00532A78, 0x18

dlabel msg.2_00532A78
    /* 00532A78 */ .space 0x18

nonmatching fname.13, 0x80

dlabel fname.13
    /* 00532A90 */ .space 0x80

nonmatching sort, 0x800

dlabel sort
    /* 00532B10 */ .space 0x800

nonmatching mw_list, 0x1340

dlabel mw_list
    /* 00533310 */ .space 0x1340

nonmatching D_00534650, 0x4C0

dlabel D_00534650
    /* 00534650 */ .space 0x4C0

nonmatching UpPara, 0x10

dlabel UpPara
    /* 00534B10 */ .space 0x10

nonmatching MenuCharParty, 0x10

dlabel MenuCharParty
    /* 00534B20 */ .space 0x10

nonmatching paraUnit, 0x300

dlabel paraUnit
    /* 00534B30 */ .space 0x300

nonmatching TairetuRot, 0x10

dlabel TairetuRot
    /* 00534E30 */ .space 0x10

nonmatching TairetuPos, 0x10

dlabel TairetuPos
    /* 00534E40 */ .space 0x10

nonmatching mmsg.9, 0x80

dlabel mmsg.9
    /* 00534E50 */ .space 0x80

nonmatching AgwsNo, 0x20

dlabel AgwsNo
    /* 00534ED0 */ .space 0x20

nonmatching AgwsWinSP, 0x10

dlabel AgwsWinSP
    /* 00534EF0 */ .space 0x10

nonmatching SeisanCN, 0x8

dlabel SeisanCN
    /* 00534F00 */ .space 0x08

nonmatching D_00534F08, 0x45

dlabel D_00534F08
    /* 00534F08 */ .space 0x45

nonmatching D_00534F4D, 0x63

dlabel D_00534F4D
    /* 00534F4D */ .space 0x63

nonmatching ShopData, 0x8

dlabel ShopData
    /* 00534FB0 */ .space 0x08

nonmatching D_00534FB8, 0x20

dlabel D_00534FB8
    /* 00534FB8 */ .space 0x20

nonmatching D_00534FD8, 0x28

dlabel D_00534FD8
    /* 00534FD8 */ .space 0x28

nonmatching D_00535000, 0x28

dlabel D_00535000
    /* 00535000 */ .space 0x28

nonmatching D_00535028, 0x28

dlabel D_00535028
    /* 00535028 */ .space 0x28

nonmatching D_00535050, 0x28

dlabel D_00535050
    /* 00535050 */ .space 0x28

nonmatching D_00535078, 0x28

dlabel D_00535078
    /* 00535078 */ .space 0x28

nonmatching D_005350A0, 0x28

dlabel D_005350A0
    /* 005350A0 */ .space 0x28

nonmatching D_005350C8, 0x28

dlabel D_005350C8
    /* 005350C8 */ .space 0x28

nonmatching D_005350F0, 0x28

dlabel D_005350F0
    /* 005350F0 */ .space 0x28

nonmatching D_00535118, 0x8

dlabel D_00535118
    /* 00535118 */ .space 0x08

nonmatching MenuTecParty, 0x10

dlabel MenuTecParty
    /* 00535120 */ .space 0x10

nonmatching MenuSkillParty, 0x10

dlabel MenuSkillParty
    /* 00535130 */ .space 0x10

nonmatching uwamono_dat, 0xAEC0

dlabel uwamono_dat
    /* 00535140 */ .space 0xAEC0

nonmatching D_00540000, 0x54

dlabel D_00540000
    /* 00540000 */ .space 0x54

nonmatching D_00540054, 0x4902

dlabel D_00540054
    /* 00540054 */ .space 0x4902

nonmatching D_00544956, 0x2FF

dlabel D_00544956
    /* 00544956 */ .space 0x2FF

nonmatching D_00544C55, 0x6F0

dlabel D_00544C55
    /* 00544C55 */ .space 0x6F0

nonmatching D_00545345, 0xAE11

dlabel D_00545345
    /* 00545345 */ .space 0xAE11

nonmatching D_00550156, 0x101DA

dlabel D_00550156
    /* 00550156 */ .space 0x101DA

nonmatching D_00560330, 0x25F8

dlabel D_00560330
    /* 00560330 */ .space 0x25F8

nonmatching D_00562928, 0x13

dlabel D_00562928
    /* 00562928 */ .space 0x13

nonmatching D_0056293B, 0xD717

dlabel D_0056293B
    /* 0056293B */ .space 0xD717

nonmatching D_00570052, 0x109

dlabel D_00570052
    /* 00570052 */ .space 0x109

nonmatching D_0057015B, 0x3FB0

dlabel D_0057015B
    /* 0057015B */ .space 0x3FB0

nonmatching D_0057410B, 0x200

dlabel D_0057410B
    /* 0057410B */ .space 0x200

nonmatching D_0057430B, 0x10239

dlabel D_0057430B
    /* 0057430B */ .space 0x10239

nonmatching D_00584544, 0xBFC

dlabel D_00584544
    /* 00584544 */ .space 0xBFC

nonmatching cpos_00585140, 0x40

dlabel cpos_00585140
    /* 00585140 */ .space 0x40

nonmatching wpos, 0xC

dlabel wpos
    /* 00585180 */ .space 0x0C

nonmatching D_0058518C, 0x34

dlabel D_0058518C
    /* 0058518C */ .space 0x34

nonmatching wvec, 0x40

dlabel wvec
    /* 005851C0 */ .space 0x40

nonmatching cpos_00585200, 0x40

dlabel cpos_00585200
    /* 00585200 */ .space 0x40

nonmatching pos1, 0x40

dlabel pos1
    /* 00585240 */ .space 0x40

nonmatching pos2, 0x40

dlabel pos2
    /* 00585280 */ .space 0x40

nonmatching box1, 0x10

dlabel box1
    /* 005852C0 */ .space 0x10

nonmatching box2, 0x10

dlabel box2
    /* 005852D0 */ .space 0x10

nonmatching hitpos, 0x10

dlabel hitpos
    /* 005852E0 */ .space 0x10

nonmatching box3, 0x10

dlabel box3
    /* 005852F0 */ .space 0x10

nonmatching box4, 0x10

dlabel box4
    /* 00585300 */ .space 0x10

nonmatching path.0, 0x80

dlabel path.0
    /* 00585310 */ .space 0x80

nonmatching name.1, 0x40

dlabel name.1
    /* 00585390 */ .space 0x40

nonmatching prm.8, 0x30

dlabel prm.8
    /* 005853D0 */ .space 0x30

nonmatching dmyActor.12, 0xA70

dlabel dmyActor.12
    /* 00585400 */ .space 0xA70

nonmatching prm.13, 0x28

dlabel prm.13
    /* 00585E70 */ .space 0x28

nonmatching cfs, 0x268

dlabel cfs
    /* 00585E98 */ .space 0x268

nonmatching _eftBuffer, 0xA05F

dlabel _eftBuffer
    /* 00586100 */ .space 0xA05F

nonmatching D_0059015F, 0xFEDC

dlabel D_0059015F
    /* 0059015F */ .space 0xFEDC

nonmatching D_005A003B, 0x18

dlabel D_005A003B
    /* 005A003B */ .space 0x18

nonmatching D_005A0053, 0x45F3

dlabel D_005A0053
    /* 005A0053 */ .space 0x45F3

nonmatching D_005A4646, 0x3

dlabel D_005A4646
    /* 005A4646 */ .space 0x03

nonmatching D_005A4649, 0x316

dlabel D_005A4649
    /* 005A4649 */ .space 0x316

nonmatching D_005A495F, 0x1600

dlabel D_005A495F
    /* 005A495F */ .space 0x1600

nonmatching D_005A5F5F, 0xA1A1

dlabel D_005A5F5F
    /* 005A5F5F */ .space 0xA1A1

nonmatching D_005B0100, 0x16

dlabel D_005B0100
    /* 005B0100 */ .space 0x16

nonmatching D_005B0116, 0x16

dlabel D_005B0116
    /* 005B0116 */ .space 0x16

nonmatching D_005B012C, 0x16

dlabel D_005B012C
    /* 005B012C */ .space 0x16

nonmatching D_005B0142, 0x16

dlabel D_005B0142
    /* 005B0142 */ .space 0x16

nonmatching D_005B0158, 0xC

dlabel D_005B0158
    /* 005B0158 */ .space 0x0C

nonmatching D_005B0164, 0xA

dlabel D_005B0164
    /* 005B0164 */ .space 0x0A

nonmatching D_005B016E, 0x16

dlabel D_005B016E
    /* 005B016E */ .space 0x16

nonmatching D_005B0184, 0x14

dlabel D_005B0184
    /* 005B0184 */ .space 0x14

nonmatching D_005B0198, 0x14

dlabel D_005B0198
    /* 005B0198 */ .space 0x14

nonmatching D_005B01AC, 0x14

dlabel D_005B01AC
    /* 005B01AC */ .space 0x14

nonmatching D_005B01C0, 0x14

dlabel D_005B01C0
    /* 005B01C0 */ .space 0x14

nonmatching D_005B01D4, 0x14

dlabel D_005B01D4
    /* 005B01D4 */ .space 0x14

nonmatching D_005B01E8, 0xFEDE

dlabel D_005B01E8
    /* 005B01E8 */ .space 0xFEDE

nonmatching D_005C00C6, 0x1D

dlabel D_005C00C6
    /* 005C00C6 */ .space 0x1D

nonmatching D_005C00E3, 0x628D

dlabel D_005C00E3
    /* 005C00E3 */ .space 0x628D

nonmatching D_005C6370, 0xFE

dlabel D_005C6370
    /* 005C6370 */ .space 0xFE

nonmatching D_005C646E, 0x100

dlabel D_005C646E
    /* 005C646E */ .space 0x100

nonmatching D_005C656E, 0x3FA

dlabel D_005C656E
    /* 005C656E */ .space 0x3FA

nonmatching D_005C6968, 0x1FB

dlabel D_005C6968
    /* 005C6968 */ .space 0x1FB

nonmatching D_005C6B63, 0x30C

dlabel D_005C6B63
    /* 005C6B63 */ .space 0x30C

nonmatching D_005C6E6F, 0x91D1

dlabel D_005C6E6F
    /* 005C6E6F */ .space 0x91D1

nonmatching D_005D0040, 0x128

dlabel D_005D0040
    /* 005D0040 */ .space 0x128

nonmatching D_005D0168, 0x98

dlabel D_005D0168
    /* 005D0168 */ .space 0x98

nonmatching D_005D0200, 0x40

dlabel D_005D0200
    /* 005D0200 */ .space 0x40

nonmatching D_005D0240, 0x40

dlabel D_005D0240
    /* 005D0240 */ .space 0x40

nonmatching D_005D0280, 0x40

dlabel D_005D0280
    /* 005D0280 */ .space 0x40

nonmatching D_005D02C0, 0x40

dlabel D_005D02C0
    /* 005D02C0 */ .space 0x40

nonmatching D_005D0300, 0x40

dlabel D_005D0300
    /* 005D0300 */ .space 0x40

nonmatching D_005D0340, 0x40

dlabel D_005D0340
    /* 005D0340 */ .space 0x40

nonmatching D_005D0380, 0x40

dlabel D_005D0380
    /* 005D0380 */ .space 0x40

nonmatching D_005D03C0, 0x25A4

dlabel D_005D03C0
    /* 005D03C0 */ .space 0x25A4

nonmatching D_005D2964, 0x31CA

dlabel D_005D2964
    /* 005D2964 */ .space 0x31CA

nonmatching D_005D5B2E, 0x904

dlabel D_005D5B2E
    /* 005D5B2E */ .space 0x904

nonmatching D_005D6432, 0x3

dlabel D_005D6432
    /* 005D6432 */ .space 0x03

nonmatching D_005D6435, 0x3

dlabel D_005D6435
    /* 005D6435 */ .space 0x03

nonmatching D_005D6438, 0x200

dlabel D_005D6438
    /* 005D6438 */ .space 0x200

nonmatching D_005D6638, 0x23C

dlabel D_005D6638
    /* 005D6638 */ .space 0x23C

nonmatching D_005D6874, 0xAB1

dlabel D_005D6874
    /* 005D6874 */ .space 0xAB1

nonmatching D_005D7325, 0x18D33

dlabel D_005D7325
    /* 005D7325 */ .space 0x18D33

nonmatching D_005F0058, 0xA8

dlabel D_005F0058
    /* 005F0058 */ .space 0xA8

nonmatching D_005F0100, 0x16

dlabel D_005F0100
    /* 005F0100 */ .space 0x16

nonmatching D_005F0116, 0x16

dlabel D_005F0116
    /* 005F0116 */ .space 0x16

nonmatching D_005F012C, 0x16

dlabel D_005F012C
    /* 005F012C */ .space 0x16

nonmatching D_005F0142, 0x16

dlabel D_005F0142
    /* 005F0142 */ .space 0x16

nonmatching D_005F0158, 0x16

dlabel D_005F0158
    /* 005F0158 */ .space 0x16

nonmatching D_005F016E, 0x1332

dlabel D_005F016E
    /* 005F016E */ .space 0x1332

nonmatching D_005F14A0, 0x4AC1

dlabel D_005F14A0
    /* 005F14A0 */ .space 0x4AC1

nonmatching D_005F5F61, 0x3

dlabel D_005F5F61
    /* 005F5F61 */ .space 0x03

nonmatching D_005F5F64, 0x1

dlabel D_005F5F64
    /* 005F5F64 */ .space 0x01

nonmatching D_005F5F65, 0xB

dlabel D_005F5F65
    /* 005F5F65 */ .space 0x0B

nonmatching D_005F5F70, 0x2

dlabel D_005F5F70
    /* 005F5F70 */ .space 0x02

nonmatching D_005F5F72, 0x2

dlabel D_005F5F72
    /* 005F5F72 */ .space 0x02

nonmatching D_005F5F74, 0x5FE

dlabel D_005F5F74
    /* 005F5F74 */ .space 0x5FE

nonmatching D_005F6572, 0xC2

dlabel D_005F6572
    /* 005F6572 */ .space 0xC2

nonmatching D_005F6634, 0x41

dlabel D_005F6634
    /* 005F6634 */ .space 0x41

nonmatching D_005F6675, 0xF4

dlabel D_005F6675
    /* 005F6675 */ .space 0xF4

nonmatching D_005F6769, 0x5

dlabel D_005F6769
    /* 005F6769 */ .space 0x05

nonmatching D_005F676E, 0x701

dlabel D_005F676E
    /* 005F676E */ .space 0x701

nonmatching D_005F6E6F, 0x5

dlabel D_005F6E6F
    /* 005F6E6F */ .space 0x05

nonmatching D_005F6E74, 0xF4

dlabel D_005F6E74
    /* 005F6E74 */ .space 0xF4

nonmatching D_005F6F68, 0x5

dlabel D_005F6F68
    /* 005F6F68 */ .space 0x05

nonmatching D_005F6F6D, 0x2FD

dlabel D_005F6F6D
    /* 005F6F6D */ .space 0x2FD

nonmatching D_005F726A, 0x105

dlabel D_005F726A
    /* 005F726A */ .space 0x105

nonmatching D_005F736F, 0x6

dlabel D_005F736F
    /* 005F736F */ .space 0x06

nonmatching D_005F7375, 0xEE

dlabel D_005F7375
    /* 005F7375 */ .space 0xEE

nonmatching D_005F7463, 0x6

dlabel D_005F7463
    /* 005F7463 */ .space 0x06

nonmatching D_005F7469, 0x104

dlabel D_005F7469
    /* 005F7469 */ .space 0x104

nonmatching D_005F756D, 0x208

dlabel D_005F756D
    /* 005F756D */ .space 0x208

nonmatching D_005F7775, 0x100

dlabel D_005F7775
    /* 005F7775 */ .space 0x100

nonmatching D_005F7875, 0x1

dlabel D_005F7875
    /* 005F7875 */ .space 0x01

nonmatching D_005F7876, 0x5CB

dlabel D_005F7876
    /* 005F7876 */ .space 0x5CB

nonmatching D_005F7E41, 0x32DE

dlabel D_005F7E41
    /* 005F7E41 */ .space 0x32DE

nonmatching D_005FB11F, 0x390E

dlabel D_005FB11F
    /* 005FB11F */ .space 0x390E

nonmatching D_005FEA2D, 0x15D3

dlabel D_005FEA2D
    /* 005FEA2D */ .space 0x15D3

nonmatching D_00600000, 0x4E

dlabel D_00600000
    /* 00600000 */ .space 0x4E

nonmatching D_0060004E, 0x1B1

dlabel D_0060004E
    /* 0060004E */ .space 0x1B1

nonmatching D_006001FF, 0x362E

dlabel D_006001FF
    /* 006001FF */ .space 0x362E

nonmatching D_0060382D, 0x37D3

dlabel D_0060382D
    /* 0060382D */ .space 0x37D3

nonmatching D_00607000, 0x202D

dlabel D_00607000
    /* 00607000 */ .space 0x202D

nonmatching D_0060902D, 0x524E

dlabel D_0060902D
    /* 0060902D */ .space 0x524E

nonmatching D_0060E27B, 0x158E

dlabel D_0060E27B
    /* 0060E27B */ .space 0x158E

nonmatching D_0060F809, 0x96B

dlabel D_0060F809
    /* 0060F809 */ .space 0x96B

nonmatching D_00610174, 0x5DF9

dlabel D_00610174
    /* 00610174 */ .space 0x5DF9

nonmatching D_00615F6D, 0xA

dlabel D_00615F6D
    /* 00615F6D */ .space 0x0A

nonmatching D_00615F77, 0x2F8

dlabel D_00615F77
    /* 00615F77 */ .space 0x2F8

nonmatching D_0061626F, 0x6FD

dlabel D_0061626F
    /* 0061626F */ .space 0x6FD

nonmatching D_0061696C, 0x8F9

dlabel D_0061696C
    /* 0061696C */ .space 0x8F9

nonmatching D_00617265, 0x8D9B

dlabel D_00617265
    /* 00617265 */ .space 0x8D9B

nonmatching D_00620000, 0x5B

dlabel D_00620000
    /* 00620000 */ .space 0x5B

nonmatching D_0062005B, 0x5

dlabel D_0062005B
    /* 0062005B */ .space 0x05

nonmatching D_00620060, 0xFB4

dlabel D_00620060
    /* 00620060 */ .space 0xFB4

nonmatching D_00621014, 0x10

dlabel D_00621014
    /* 00621014 */ .space 0x10

nonmatching D_00621024, 0x800

dlabel D_00621024
    /* 00621024 */ .space 0x800

nonmatching D_00621824, 0x1

dlabel D_00621824
    /* 00621824 */ .space 0x01

nonmatching D_00621825, 0x1FFC

dlabel D_00621825
    /* 00621825 */ .space 0x1FFC

nonmatching D_00623821, 0x274C

dlabel D_00623821
    /* 00623821 */ .space 0x274C

nonmatching D_00625F6D, 0xA

dlabel D_00625F6D
    /* 00625F6D */ .space 0x0A

nonmatching D_00625F77, 0x5EF

dlabel D_00625F77
    /* 00625F77 */ .space 0x5EF

nonmatching D_00626566, 0x9AFD

dlabel D_00626566
    /* 00626566 */ .space 0x9AFD

nonmatching D_00630063, 0x113

dlabel D_00630063
    /* 00630063 */ .space 0x113

nonmatching D_00630176, 0x23E5

dlabel D_00630176
    /* 00630176 */ .space 0x23E5

nonmatching D_0063255B, 0x4CD3

dlabel D_0063255B
    /* 0063255B */ .space 0x4CD3

nonmatching D_0063722E, 0x9DE8

dlabel D_0063722E
    /* 0063722E */ .space 0x9DE8

nonmatching D_00641016, 0x80B

dlabel D_00641016
    /* 00641016 */ .space 0x80B

nonmatching D_00641821, 0xCFF

dlabel D_00641821
    /* 00641821 */ .space 0xCFF

nonmatching D_00642520, 0x45

dlabel D_00642520
    /* 00642520 */ .space 0x45

nonmatching D_00642565, 0xBC0

dlabel D_00642565
    /* 00642565 */ .space 0xBC0

nonmatching D_00643125, 0x100

dlabel D_00643125
    /* 00643125 */ .space 0x100

nonmatching D_00643225, 0x41

dlabel D_00643225
    /* 00643225 */ .space 0x41

nonmatching D_00643266, 0x3

dlabel D_00643266
    /* 00643266 */ .space 0x03

nonmatching D_00643269, 0x3

dlabel D_00643269
    /* 00643269 */ .space 0x03

nonmatching D_0064326C, 0xB9

dlabel D_0064326C
    /* 0064326C */ .space 0xB9

nonmatching D_00643325, 0x100

dlabel D_00643325
    /* 00643325 */ .space 0x100

nonmatching D_00643425, 0x100

dlabel D_00643425
    /* 00643425 */ .space 0x100

nonmatching D_00643525, 0x100

dlabel D_00643525
    /* 00643525 */ .space 0x100

nonmatching D_00643625, 0x200

dlabel D_00643625
    /* 00643625 */ .space 0x200

nonmatching D_00643825, 0x293F

dlabel D_00643825
    /* 00643825 */ .space 0x293F

nonmatching D_00646164, 0x1

dlabel D_00646164
    /* 00646164 */ .space 0x01

nonmatching D_00646165, 0xA

dlabel D_00646165
    /* 00646165 */ .space 0x0A

nonmatching D_0064616F, 0x403

dlabel D_0064616F
    /* 0064616F */ .space 0x403

nonmatching D_00646572, 0x2

dlabel D_00646572
    /* 00646572 */ .space 0x02

nonmatching D_00646574, 0x6

dlabel D_00646574
    /* 00646574 */ .space 0x06

nonmatching D_0064657A, 0x3B4

dlabel D_0064657A
    /* 0064657A */ .space 0x3B4

nonmatching D_0064692E, 0x435

dlabel D_0064692E
    /* 0064692E */ .space 0x435

nonmatching D_00646D63, 0x10

dlabel D_00646D63
    /* 00646D63 */ .space 0x10

nonmatching D_00646D73, 0xEE

dlabel D_00646D73
    /* 00646D73 */ .space 0xEE

nonmatching D_00646E61, 0x8

dlabel D_00646E61
    /* 00646E61 */ .space 0x08

nonmatching D_00646E69, 0xC

dlabel D_00646E69
    /* 00646E69 */ .space 0x0C

nonmatching D_00646E75, 0x4FE

dlabel D_00646E75
    /* 00646E75 */ .space 0x4FE

nonmatching D_00647373, 0x8E05

dlabel D_00647373
    /* 00647373 */ .space 0x8E05

nonmatching D_00650178, 0xEA0

dlabel D_00650178
    /* 00650178 */ .space 0xEA0

nonmatching D_00651018, 0x809

dlabel D_00651018
    /* 00651018 */ .space 0x809

nonmatching D_00651821, 0x4B40

dlabel D_00651821
    /* 00651821 */ .space 0x4B40

nonmatching D_00656361, 0x10E

dlabel D_00656361
    /* 00656361 */ .space 0x10E

nonmatching D_0065646F, 0x7F3

dlabel D_0065646F
    /* 0065646F */ .space 0x7F3

nonmatching D_00656C62, 0x107

dlabel D_00656C62
    /* 00656C62 */ .space 0x107

nonmatching D_00656D69, 0x6

dlabel D_00656D69
    /* 00656D69 */ .space 0x06

nonmatching D_00656D6F, 0xF6

dlabel D_00656D6F
    /* 00656D6F */ .space 0xF6

nonmatching D_00656E65, 0x40A

dlabel D_00656E65
    /* 00656E65 */ .space 0x40A

nonmatching D_0065726F, 0x6

dlabel D_0065726F
    /* 0065726F */ .space 0x06

nonmatching D_00657275, 0xE0

dlabel D_00657275
    /* 00657275 */ .space 0xE0

nonmatching D_00657355, 0x30C

dlabel D_00657355
    /* 00657355 */ .space 0x30C

nonmatching D_00657661, 0x8

dlabel D_00657661
    /* 00657661 */ .space 0x08

nonmatching D_00657669, 0x3

dlabel D_00657669
    /* 00657669 */ .space 0x03

nonmatching D_0065766C, 0x3

dlabel D_0065766C
    /* 0065766C */ .space 0x03

nonmatching D_0065766F, 0x3

dlabel D_0065766F
    /* 0065766F */ .space 0x03

nonmatching D_00657672, 0x2F3

dlabel D_00657672
    /* 00657672 */ .space 0x2F3

nonmatching D_00657965, 0x2020

dlabel D_00657965
    /* 00657965 */ .space 0x2020

nonmatching D_00659985, 0xF7B

dlabel D_00659985
    /* 00659985 */ .space 0xF7B

nonmatching _scheduler, 0xA0

dlabel _scheduler
    /* 0065A900 */ .space 0xA0

nonmatching D_0065A9A0, 0x10

dlabel D_0065A9A0
    /* 0065A9A0 */ .space 0x10

nonmatching D_0065A9B0, 0x600

dlabel D_0065A9B0
    /* 0065A9B0 */ .space 0x600

nonmatching D_0065AFB0, 0x1C

dlabel D_0065AFB0
    /* 0065AFB0 */ .space 0x1C

nonmatching D_0065AFCC, 0x64

dlabel D_0065AFCC
    /* 0065AFCC */ .space 0x64

nonmatching D_0065B030, 0x334

dlabel D_0065B030
    /* 0065B030 */ .space 0x334

nonmatching D_0065B364, 0x64C0

dlabel D_0065B364
    /* 0065B364 */ .space 0x64C0

nonmatching D_00661824, 0xD19

dlabel D_00661824
    /* 00661824 */ .space 0xD19

nonmatching D_0066253D, 0x2E4

dlabel D_0066253D
    /* 0066253D */ .space 0x2E4

nonmatching D_00662821, 0xA0D

dlabel D_00662821
    /* 00662821 */ .space 0xA0D

nonmatching D_0066322E, 0x36

dlabel D_0066322E
    /* 0066322E */ .space 0x36

nonmatching D_00663264, 0x5

dlabel D_00663264
    /* 00663264 */ .space 0x05

nonmatching D_00663269, 0x3

dlabel D_00663269
    /* 00663269 */ .space 0x03

nonmatching D_0066326C, 0xC2

dlabel D_0066326C
    /* 0066326C */ .space 0xC2

nonmatching D_0066332E, 0x4F7

dlabel D_0066332E
    /* 0066332E */ .space 0x4F7

nonmatching D_00663825, 0x2B3A

dlabel D_00663825
    /* 00663825 */ .space 0x2B3A

nonmatching D_0066635F, 0x2F0

dlabel D_0066635F
    /* 0066635F */ .space 0x2F0

nonmatching D_0066664F, 0x20

dlabel D_0066664F
    /* 0066664F */ .space 0x20

nonmatching D_0066666F, 0x7DA

dlabel D_0066666F
    /* 0066666F */ .space 0x7DA

nonmatching D_00666E49, 0x9335

dlabel D_00666E49
    /* 00666E49 */ .space 0x9335

nonmatching D_0067017E, 0x16A6

dlabel D_0067017E
    /* 0067017E */ .space 0x16A6

nonmatching D_00671824, 0x5641

dlabel D_00671824
    /* 00671824 */ .space 0x5641

nonmatching D_00676E65, 0x4

dlabel D_00676E65
    /* 00676E65 */ .space 0x04

nonmatching D_00676E69, 0x201

dlabel D_00676E69
    /* 00676E69 */ .space 0x201

nonmatching D_0067706A, 0x303

dlabel D_0067706A
    /* 0067706A */ .space 0x303

nonmatching D_0067736D, 0xA4B7

dlabel D_0067736D
    /* 0067736D */ .space 0xA4B7

nonmatching D_00681824, 0x2869

dlabel D_00681824
    /* 00681824 */ .space 0x2869

nonmatching D_0068408D, 0x1EA8

dlabel D_0068408D
    /* 0068408D */ .space 0x1EA8

nonmatching D_00685F35, 0x2F

dlabel D_00685F35
    /* 00685F35 */ .space 0x2F

nonmatching D_00685F64, 0xA

dlabel D_00685F64
    /* 00685F64 */ .space 0x0A

nonmatching D_00685F6E, 0x5

dlabel D_00685F6E
    /* 00685F6E */ .space 0x05

nonmatching D_00685F73, 0x6

dlabel D_00685F73
    /* 00685F73 */ .space 0x06

nonmatching D_00685F79, 0x3E8

dlabel D_00685F79
    /* 00685F79 */ .space 0x3E8

nonmatching D_00686361, 0x11

dlabel D_00686361
    /* 00686361 */ .space 0x11

nonmatching D_00686372, 0x2

dlabel D_00686372
    /* 00686372 */ .space 0x02

nonmatching D_00686374, 0x10F3

dlabel D_00686374
    /* 00686374 */ .space 0x10F3

nonmatching D_00687467, 0x8D1A

dlabel D_00687467
    /* 00687467 */ .space 0x8D1A

nonmatching D_00690181, 0x16A3

dlabel D_00690181
    /* 00690181 */ .space 0x16A3

nonmatching D_00691824, 0x1A40

dlabel D_00691824
    /* 00691824 */ .space 0x1A40

nonmatching D_00693264, 0x2

dlabel D_00693264
    /* 00693264 */ .space 0x02

nonmatching D_00693266, 0x6

dlabel D_00693266
    /* 00693266 */ .space 0x06

nonmatching D_0069326C, 0x3607

dlabel D_0069326C
    /* 0069326C */ .space 0x3607

nonmatching D_00696873, 0x1FC

dlabel D_00696873
    /* 00696873 */ .space 0x1FC

nonmatching D_00696A6F, 0x7F8

dlabel D_00696A6F
    /* 00696A6F */ .space 0x7F8

nonmatching D_00697267, 0x8D99

dlabel D_00697267
    /* 00697267 */ .space 0x8D99

nonmatching D_006A0000, 0x1824

dlabel D_006A0000
    /* 006A0000 */ .space 0x1824

nonmatching D_006A1824, 0xE8DC

dlabel D_006A1824
    /* 006A1824 */ .space 0xE8DC

nonmatching _lineData, 0x84

dlabel _lineData
    /* 006B0100 */ .space 0x84

nonmatching D_006B0184, 0x61DD

dlabel D_006B0184
    /* 006B0184 */ .space 0x61DD

nonmatching D_006B6361, 0xE

dlabel D_006B6361
    /* 006B6361 */ .space 0x0E

nonmatching D_006B636F, 0xCF7

dlabel D_006B636F
    /* 006B636F */ .space 0xCF7

nonmatching D_006B7066, 0x3B8A

dlabel D_006B7066
    /* 006B7066 */ .space 0x3B8A

nonmatching D_006BABF0, 0x8674

dlabel D_006BABF0
    /* 006BABF0 */ .space 0x8674

nonmatching D_006C3264, 0x2

dlabel D_006C3264
    /* 006C3264 */ .space 0x02

nonmatching D_006C3266, 0x3

dlabel D_006C3266
    /* 006C3266 */ .space 0x03

nonmatching D_006C3269, 0x32FA

dlabel D_006C3269
    /* 006C3269 */ .space 0x32FA

nonmatching D_006C6563, 0x6FE

dlabel D_006C6563
    /* 006C6563 */ .space 0x6FE

nonmatching D_006C6C61, 0x14

dlabel D_006C6C61
    /* 006C6C61 */ .space 0x14

nonmatching D_006C6C75, 0x9512

dlabel D_006C6C75
    /* 006C6C75 */ .space 0x9512

nonmatching D_006D0187, 0x1DE6

dlabel D_006D0187
    /* 006D0187 */ .space 0x1DE6

nonmatching D_006D1F6D, 0x3FFF

dlabel D_006D1F6D
    /* 006D1F6D */ .space 0x3FFF

nonmatching D_006D5F6C, 0x201

dlabel D_006D5F6C
    /* 006D5F6C */ .space 0x201

nonmatching D_006D616D, 0x407

dlabel D_006D616D
    /* 006D616D */ .space 0x407

nonmatching D_006D6574, 0x3F4

dlabel D_006D6574
    /* 006D6574 */ .space 0x3F4

nonmatching D_006D6968, 0x8D9

dlabel D_006D6968
    /* 006D6968 */ .space 0x8D9

nonmatching D_006D7241, 0xDC03

dlabel D_006D7241
    /* 006D7241 */ .space 0xDC03

nonmatching D_006E4E44, 0x1321

dlabel D_006E4E44
    /* 006E4E44 */ .space 0x1321

nonmatching D_006E6165, 0x8

dlabel D_006E6165
    /* 006E6165 */ .space 0x08

nonmatching D_006E616D, 0x9

dlabel D_006E616D
    /* 006E616D */ .space 0x09

nonmatching D_006E6176, 0x5F3

dlabel D_006E6176
    /* 006E6176 */ .space 0x5F3

nonmatching D_006E6769, 0x800

dlabel D_006E6769
    /* 006E6769 */ .space 0x800

nonmatching D_006E6F69, 0x7

dlabel D_006E6F69
    /* 006E6F69 */ .space 0x07

nonmatching D_006E6F70, 0x2

dlabel D_006E6F70
    /* 006E6F70 */ .space 0x02

nonmatching D_006E6F72, 0x303

dlabel D_006E6F72
    /* 006E6F72 */ .space 0x303

nonmatching D_006E7275, 0x2F9

dlabel D_006E7275
    /* 006E7275 */ .space 0x2F9

nonmatching D_006E756E, 0x9546

dlabel D_006E756E
    /* 006E756E */ .space 0x9546

nonmatching D_006F0AB4, 0x64C

dlabel D_006F0AB4
    /* 006F0AB4 */ .space 0x64C

nonmatching _ptAlloc, 0x3D20

dlabel _ptAlloc
    /* 006F1100 */ .space 0x3D20

nonmatching D_006F4E20, 0xB1E0

dlabel D_006F4E20
    /* 006F4E20 */ .space 0xB1E0

nonmatching D_00700000, 0x38

dlabel D_00700000
    /* 00700000 */ .space 0x38

nonmatching D_00700038, 0x48

dlabel D_00700038
    /* 00700038 */ .space 0x48

nonmatching D_00700080, 0x24A0

dlabel D_00700080
    /* 00700080 */ .space 0x24A0

nonmatching D_00702520, 0x194

dlabel D_00702520
    /* 00702520 */ .space 0x194

nonmatching D_007026B4, 0x1E4D

dlabel D_007026B4
    /* 007026B4 */ .space 0x1E4D

nonmatching D_00704501, 0x300

dlabel D_00704501
    /* 00704501 */ .space 0x300

nonmatching D_00704801, 0x196C

dlabel D_00704801
    /* 00704801 */ .space 0x196C

nonmatching D_0070616D, 0x7FE

dlabel D_0070616D
    /* 0070616D */ .space 0x7FE

nonmatching D_0070696B, 0x603

dlabel D_0070696B
    /* 0070696B */ .space 0x603

nonmatching D_00706F6E, 0x2

dlabel D_00706F6E
    /* 00706F6E */ .space 0x02

nonmatching D_00706F70, 0x1D5

dlabel D_00706F70
    /* 00706F70 */ .space 0x1D5

nonmatching D_00707145, 0x220

dlabel D_00707145
    /* 00707145 */ .space 0x220

nonmatching D_00707365, 0x1FF

dlabel D_00707365
    /* 00707365 */ .space 0x1FF

nonmatching D_00707564, 0xA

dlabel D_00707564
    /* 00707564 */ .space 0x0A

nonmatching D_0070756E, 0x8ADA

dlabel D_0070756E
    /* 0070756E */ .space 0x8ADA

nonmatching D_00710048, 0x22

dlabel D_00710048
    /* 00710048 */ .space 0x22

nonmatching D_0071006A, 0xDE

dlabel D_0071006A
    /* 0071006A */ .space 0xDE

nonmatching D_00710148, 0x15FFE

dlabel D_00710148
    /* 00710148 */ .space 0x15FFE

nonmatching D_00726146, 0x41E

dlabel D_00726146
    /* 00726146 */ .space 0x41E

nonmatching D_00726564, 0x3

dlabel D_00726564
    /* 00726564 */ .space 0x03

nonmatching D_00726567, 0x2

dlabel D_00726567
    /* 00726567 */ .space 0x02

nonmatching D_00726569, 0xA00

dlabel D_00726569
    /* 00726569 */ .space 0xA00

nonmatching D_00726F69, 0x3

dlabel D_00726F69
    /* 00726F69 */ .space 0x03

nonmatching D_00726F6C, 0x3FE

dlabel D_00726F6C
    /* 00726F6C */ .space 0x3FE

nonmatching D_0072736A, 0x8D96

dlabel D_0072736A
    /* 0072736A */ .space 0x8D96

nonmatching D_00730100, 0x16

dlabel D_00730100
    /* 00730100 */ .space 0x16

nonmatching D_00730116, 0x16

dlabel D_00730116
    /* 00730116 */ .space 0x16

nonmatching D_0073012C, 0x16

dlabel D_0073012C
    /* 0073012C */ .space 0x16

nonmatching D_00730142, 0x16

dlabel D_00730142
    /* 00730142 */ .space 0x16

nonmatching D_00730158, 0x16

dlabel D_00730158
    /* 00730158 */ .space 0x16

nonmatching D_0073016E, 0x16

dlabel D_0073016E
    /* 0073016E */ .space 0x16

nonmatching D_00730184, 0x14

dlabel D_00730184
    /* 00730184 */ .space 0x14

nonmatching D_00730198, 0x14

dlabel D_00730198
    /* 00730198 */ .space 0x14

nonmatching D_007301AC, 0x14

dlabel D_007301AC
    /* 007301AC */ .space 0x14

nonmatching D_007301C0, 0x234B

dlabel D_007301C0
    /* 007301C0 */ .space 0x234B

nonmatching D_0073250B, 0x50

dlabel D_0073250B
    /* 0073250B */ .space 0x50

nonmatching D_0073255B, 0x3F11

dlabel D_0073255B
    /* 0073255B */ .space 0x3F11

nonmatching D_0073646C, 0x500

dlabel D_0073646C
    /* 0073646C */ .space 0x500

nonmatching D_0073696C, 0x3F5

dlabel D_0073696C
    /* 0073696C */ .space 0x3F5

nonmatching D_00736D61, 0x10E

dlabel D_00736D61
    /* 00736D61 */ .space 0x10E

nonmatching D_00736E6F, 0x3F6

dlabel D_00736E6F
    /* 00736E6F */ .space 0x3F6

nonmatching D_00737265, 0x10B

dlabel D_00737265
    /* 00737265 */ .space 0x10B

nonmatching D_00737370, 0xE0

dlabel D_00737370
    /* 00737370 */ .space 0xE0

nonmatching D_00737450, 0x318

dlabel D_00737450
    /* 00737450 */ .space 0x318

nonmatching D_00737768, 0x3161

dlabel D_00737768
    /* 00737768 */ .space 0x3161

nonmatching D_0073A8C9, 0x7758

dlabel D_0073A8C9
    /* 0073A8C9 */ .space 0x7758

nonmatching D_00742021, 0x800

dlabel D_00742021
    /* 00742021 */ .space 0x800

nonmatching D_00742821, 0x2EE0

dlabel D_00742821
    /* 00742821 */ .space 0x2EE0

nonmatching D_00745701, 0xA63

dlabel D_00745701
    /* 00745701 */ .space 0xA63

nonmatching D_00746164, 0x1FD

dlabel D_00746164
    /* 00746164 */ .space 0x1FD

nonmatching D_00746361, 0x4

dlabel D_00746361
    /* 00746361 */ .space 0x04

nonmatching D_00746365, 0x1EE

dlabel D_00746365
    /* 00746365 */ .space 0x1EE

nonmatching D_00746553, 0x14

dlabel D_00746553
    /* 00746553 */ .space 0x14

nonmatching D_00746567, 0xB

dlabel D_00746567
    /* 00746567 */ .space 0x0B

nonmatching D_00746572, 0xFD

dlabel D_00746572
    /* 00746572 */ .space 0xFD

nonmatching D_0074666F, 0x1F8

dlabel D_0074666F
    /* 0074666F */ .space 0x1F8

nonmatching D_00746867, 0x107

dlabel D_00746867
    /* 00746867 */ .space 0x107

nonmatching D_0074696E, 0xA

dlabel D_0074696E
    /* 0074696E */ .space 0x0A

nonmatching D_00746978, 0x2C9

dlabel D_00746978
    /* 00746978 */ .space 0x2C9

nonmatching D_00746C41, 0x34

dlabel D_00746C41
    /* 00746C41 */ .space 0x34

nonmatching D_00746C75, 0x1F0

dlabel D_00746C75
    /* 00746C75 */ .space 0x1F0

nonmatching D_00746E65, 0x4

dlabel D_00746E65
    /* 00746E65 */ .space 0x04

nonmatching D_00746E69, 0x103

dlabel D_00746E69
    /* 00746E69 */ .space 0x103

nonmatching D_00746F6C, 0x1

dlabel D_00746F6C
    /* 00746F6C */ .space 0x01

nonmatching D_00746F6D, 0x3F4

dlabel D_00746F6D
    /* 00746F6D */ .space 0x3F4

nonmatching D_00747361, 0x4

dlabel D_00747361
    /* 00747361 */ .space 0x04

nonmatching D_00747365, 0x7

dlabel D_00747365
    /* 00747365 */ .space 0x07

nonmatching D_0074736C, 0x204

dlabel D_0074736C
    /* 0074736C */ .space 0x204

nonmatching D_00747570, 0xF5

dlabel D_00747570
    /* 00747570 */ .space 0xF5

nonmatching D_00747665, 0x200

dlabel D_00747665
    /* 00747665 */ .space 0x200

nonmatching D_00747865, 0xF

dlabel D_00747865
    /* 00747865 */ .space 0x0F

nonmatching D_00747874, 0xAF46

dlabel D_00747874
    /* 00747874 */ .space 0xAF46

nonmatching D_007527BA, 0x45AB

dlabel D_007527BA
    /* 007527BA */ .space 0x45AB

nonmatching D_00756D65, 0xDE9C

dlabel D_00756D65
    /* 00756D65 */ .space 0xDE9C

nonmatching D_00764C01, 0x2073

dlabel D_00764C01
    /* 00764C01 */ .space 0x2073

nonmatching D_00766C74, 0x948C

dlabel D_00766C74
    /* 00766C74 */ .space 0x948C

nonmatching D_00770100, 0x16

dlabel D_00770100
    /* 00770100 */ .space 0x16

nonmatching D_00770116, 0x16

dlabel D_00770116
    /* 00770116 */ .space 0x16

nonmatching D_0077012C, 0x16

dlabel D_0077012C
    /* 0077012C */ .space 0x16

nonmatching D_00770142, 0x16

dlabel D_00770142
    /* 00770142 */ .space 0x16

nonmatching D_00770158, 0x16

dlabel D_00770158
    /* 00770158 */ .space 0x16

nonmatching D_0077016E, 0x93

dlabel D_0077016E
    /* 0077016E */ .space 0x93

nonmatching D_00770201, 0x5D6B

dlabel D_00770201
    /* 00770201 */ .space 0x5D6B

nonmatching D_00775F6C, 0x602

dlabel D_00775F6C
    /* 00775F6C */ .space 0x602

nonmatching D_0077656E, 0x9FE

dlabel D_0077656E
    /* 0077656E */ .space 0x9FE

nonmatching D_00776F6C, 0x90AB

dlabel D_00776F6C
    /* 00776F6C */ .space 0x90AB

nonmatching D_00780017, 0x61

dlabel D_00780017
    /* 00780017 */ .space 0x61

nonmatching D_00780078, 0x30AD

dlabel D_00780078
    /* 00780078 */ .space 0x30AD

nonmatching D_00783125, 0x100

dlabel D_00783125
    /* 00783125 */ .space 0x100

nonmatching D_00783225, 0x200

dlabel D_00783225
    /* 00783225 */ .space 0x200

nonmatching D_00783425, 0xB

dlabel D_00783425
    /* 00783425 */ .space 0x0B

nonmatching D_00783430, 0x1F5

dlabel D_00783430
    /* 00783430 */ .space 0x1F5

nonmatching D_00783625, 0x2F47

dlabel D_00783625
    /* 00783625 */ .space 0x2F47

nonmatching D_0078656C, 0x8

dlabel D_0078656C
    /* 0078656C */ .space 0x08

nonmatching D_00786574, 0xF04

dlabel D_00786574
    /* 00786574 */ .space 0xF04

nonmatching D_00787478, 0xA498

dlabel D_00787478
    /* 00787478 */ .space 0xA498

nonmatching _savePrm, 0x2800

dlabel _savePrm
    /* 00791910 */ .space 0x2800

nonmatching _battleData, 0xC

dlabel _battleData
    /* 00794110 */ .space 0x0C

nonmatching D_0079411C, 0x4

dlabel D_0079411C
    /* 0079411C */ .space 0x04

nonmatching D_00794120, 0x6

dlabel D_00794120
    /* 00794120 */ .space 0x06

nonmatching D_00794126, 0x6A

dlabel D_00794126
    /* 00794126 */ .space 0x6A

nonmatching D_00794190, 0x40

dlabel D_00794190
    /* 00794190 */ .space 0x40

nonmatching D_007941D0, 0xC0

dlabel D_007941D0
    /* 007941D0 */ .space 0xC0

nonmatching D_00794290, 0x80

dlabel D_00794290
    /* 00794290 */ .space 0x80

nonmatching D_00794310, 0x24

dlabel D_00794310
    /* 00794310 */ .space 0x24

nonmatching D_00794334, 0xC

dlabel D_00794334
    /* 00794334 */ .space 0x0C

nonmatching _battlePrm, 0x30

dlabel _battlePrm
    /* 00794340 */ .space 0x30

nonmatching D_00794370, 0x10

dlabel D_00794370
    /* 00794370 */ .space 0x10

nonmatching _battleActor, 0xD80

dlabel _battleActor
    /* 00794380 */ .space 0xD80

nonmatching D_00795100, 0x20

dlabel D_00795100
    /* 00795100 */ .space 0x20

nonmatching msg.0_00795120, 0x80

dlabel msg.0_00795120
    /* 00795120 */ .space 0x80

nonmatching msg.1_007951A0, 0x80

dlabel msg.1_007951A0
    /* 007951A0 */ .space 0x80

nonmatching msg.2_00795220, 0x80

dlabel msg.2_00795220
    /* 00795220 */ .space 0x80

nonmatching _sdvSpecialBuf, 0x10

dlabel _sdvSpecialBuf
    /* 007952A0 */ .space 0x10

nonmatching _sdvAlter, 0xEA0

dlabel _sdvAlter
    /* 007952B0 */ .space 0xEA0

nonmatching D_00796150, 0x31F

dlabel D_00796150
    /* 00796150 */ .space 0x31F

nonmatching D_0079646F, 0xFC

dlabel D_0079646F
    /* 0079646F */ .space 0xFC

nonmatching D_0079656B, 0x1

dlabel D_0079656B
    /* 0079656B */ .space 0x01

nonmatching D_0079656C, 0x801

dlabel D_0079656C
    /* 0079656C */ .space 0x801

nonmatching D_00796D6D, 0x306

dlabel D_00796D6D
    /* 00796D6D */ .space 0x306

nonmatching D_00797073, 0x4CF

dlabel D_00797073
    /* 00797073 */ .space 0x4CF

nonmatching D_00797542, 0x1056E

dlabel D_00797542
    /* 00797542 */ .space 0x1056E

nonmatching stMemInfo, 0x20

dlabel stMemInfo
    /* 007A7AB0 */ .space 0x20

nonmatching mefObjBuff, 0x18547

dlabel mefObjBuff
    /* 007A7AD0 */ .space 0x18547

nonmatching D_007C0017, 0x6B9

dlabel D_007C0017
    /* 007C0017 */ .space 0x6B9

nonmatching dstr, 0x100

dlabel dstr
    /* 007C06D0 */ .space 0x100

nonmatching _dummyClass, 0x40

dlabel _dummyClass
    /* 007C07D0 */ .space 0x40

nonmatching tmpString, 0x200

dlabel tmpString
    /* 007C0810 */ .space 0x200

nonmatching value.0, 0x18

dlabel value.0
    /* 007C0A10 */ .space 0x18

nonmatching scale.0_007C0A28, 0x18

dlabel scale.0_007C0A28
    /* 007C0A28 */ .space 0x18

nonmatching scale.0_007C0A40, 0x18

dlabel scale.0_007C0A40
    /* 007C0A40 */ .space 0x18

nonmatching scale.0_007C0A58, 0x18

dlabel scale.0_007C0A58
    /* 007C0A58 */ .space 0x18

nonmatching matrixHeap, 0x20

dlabel matrixHeap
    /* 007C0A70 */ .space 0x20

nonmatching actMatrix, 0x3B575

dlabel actMatrix
    /* 007C0A90 */ .space 0x3B575

nonmatching D_007FC005, 0x5

dlabel D_007FC005
    /* 007FC005 */ .space 0x05

nonmatching D_007FC00A, 0x1FE6

dlabel D_007FC00A
    /* 007FC00A */ .space 0x1FE6

nonmatching D_007FDFF0, 0x10

dlabel D_007FDFF0
    /* 007FDFF0 */ .space 0x10

nonmatching D_007FE000, 0x2000

dlabel D_007FE000
    /* 007FE000 */ .space 0x2000

nonmatching D_00800000, 0x3

dlabel D_00800000
    /* 00800000 */ .space 0x03

nonmatching D_00800003, 0x9

dlabel D_00800003
    /* 00800003 */ .space 0x09

nonmatching D_0080000C, 0x5A

dlabel D_0080000C
    /* 0080000C */ .space 0x5A

nonmatching D_00800066, 0x1A

dlabel D_00800066
    /* 00800066 */ .space 0x1A

nonmatching D_00800080, 0xB8A

dlabel D_00800080
    /* 00800080 */ .space 0xB8A

nonmatching D_00800C0A, 0x1

dlabel D_00800C0A
    /* 00800C0A */ .space 0x01

nonmatching D_00800C0B, 0x422

dlabel D_00800C0B
    /* 00800C0B */ .space 0x422

nonmatching D_0080102D, 0x3013

dlabel D_0080102D
    /* 0080102D */ .space 0x3013

nonmatching D_00804040, 0x7ED

dlabel D_00804040
    /* 00804040 */ .space 0x7ED

nonmatching D_0080482D, 0x800

dlabel D_0080482D
    /* 0080482D */ .space 0x800

nonmatching D_0080502D, 0x1033

dlabel D_0080502D
    /* 0080502D */ .space 0x1033

nonmatching D_00806060, 0x7CD

dlabel D_00806060
    /* 00806060 */ .space 0x7CD

nonmatching D_0080682D, 0x1800

dlabel D_0080682D
    /* 0080682D */ .space 0x1800

nonmatching D_0080802D, 0x2800

dlabel D_0080802D
    /* 0080802D */ .space 0x2800

nonmatching D_0080A82D, 0x800

dlabel D_0080A82D
    /* 0080A82D */ .space 0x800

nonmatching D_0080B02D, 0x15FF8

dlabel D_0080B02D
    /* 0080B02D */ .space 0x15FF8

nonmatching D_00821025, 0xFFF

dlabel D_00821025
    /* 00821025 */ .space 0xFFF

nonmatching D_00822024, 0x15D1

dlabel D_00822024
    /* 00822024 */ .space 0x15D1

nonmatching D_008235F5, 0x1CAD1

dlabel D_008235F5
    /* 008235F5 */ .space 0x1CAD1

nonmatching D_008400C6, 0x1D

dlabel D_008400C6
    /* 008400C6 */ .space 0x1D

nonmatching D_008400E3, 0x5EA8

dlabel D_008400E3
    /* 008400E3 */ .space 0x5EA8

nonmatching D_00845F8B, 0x8A11

dlabel D_00845F8B
    /* 00845F8B */ .space 0x8A11

nonmatching D_0084E99C, 0x3685

dlabel D_0084E99C
    /* 0084E99C */ .space 0x3685

nonmatching D_00852021, 0x10000

dlabel D_00852021
    /* 00852021 */ .space 0x10000

nonmatching D_00862021, 0x1E056

dlabel D_00862021
    /* 00862021 */ .space 0x1E056

nonmatching D_00880077, 0xA19

dlabel D_00880077
    /* 00880077 */ .space 0xA19

nonmatching matrixHeapBlock, 0x400

dlabel matrixHeapBlock
    /* 00880A90 */ .space 0x400

nonmatching actInfo, 0x10

dlabel actInfo
    /* 00880E90 */ .space 0x10

nonmatching min.0, 0x10

dlabel min.0
    /* 00880EA0 */ .space 0x10

nonmatching max.1, 0x10

dlabel max.1
    /* 00880EB0 */ .space 0x10

nonmatching mpack_interest, 0x10

dlabel mpack_interest
    /* 00880EC0 */ .space 0x10

nonmatching vel.0, 0x10

dlabel vel.0
    /* 00880ED0 */ .space 0x10

nonmatching htypebuf, 0xC0

dlabel htypebuf
    /* 00880EE0 */ .space 0xC0

nonmatching sSemaParam.0, 0x18

dlabel sSemaParam.0
    /* 00880FA0 */ .space 0x18

nonmatching sThreadParam.1, 0x30

dlabel sThreadParam.1
    /* 00880FB8 */ .space 0x30

nonmatching asActiveThreadList, 0x198

dlabel asActiveThreadList
    /* 00880FE8 */ .space 0x198

nonmatching FS, 0x8

dlabel FS
    /* 00881180 */ .space 0x08

nonmatching D_00881188, 0x4

dlabel D_00881188
    /* 00881188 */ .space 0x04

nonmatching D_0088118C, 0x2

dlabel D_0088118C
    /* 0088118C */ .space 0x02

nonmatching D_0088118E, 0x2

dlabel D_0088118E
    /* 0088118E */ .space 0x02

nonmatching D_00881190, 0x2

dlabel D_00881190
    /* 00881190 */ .space 0x02

nonmatching D_00881192, 0x1

dlabel D_00881192
    /* 00881192 */ .space 0x01

nonmatching D_00881193, 0x9

dlabel D_00881193
    /* 00881193 */ .space 0x09

nonmatching D_0088119C, 0x4

dlabel D_0088119C
    /* 0088119C */ .space 0x04

nonmatching D_008811A0, 0x2860

dlabel D_008811A0
    /* 008811A0 */ .space 0x2860

nonmatching FontImage, 0xC5DD

dlabel FontImage
    /* 00883A00 */ .space 0xC5DD

nonmatching D_0088FFDD, 0x1008E

dlabel D_0088FFDD
    /* 0088FFDD */ .space 0x1008E

nonmatching D_008A006B, 0x5227

dlabel D_008A006B
    /* 008A006B */ .space 0x5227

nonmatching D_008A5292, 0xAE6E

dlabel D_008A5292
    /* 008A5292 */ .space 0xAE6E

nonmatching D_008B0100, 0x16

dlabel D_008B0100
    /* 008B0100 */ .space 0x16

nonmatching D_008B0116, 0x16

dlabel D_008B0116
    /* 008B0116 */ .space 0x16

nonmatching D_008B012C, 0x16

dlabel D_008B012C
    /* 008B012C */ .space 0x16

nonmatching D_008B0142, 0x42

dlabel D_008B0142
    /* 008B0142 */ .space 0x42

nonmatching D_008B0184, 0x14

dlabel D_008B0184
    /* 008B0184 */ .space 0x14

nonmatching D_008B0198, 0x14

dlabel D_008B0198
    /* 008B0198 */ .space 0x14

nonmatching D_008B01AC, 0x14

dlabel D_008B01AC
    /* 008B01AC */ .space 0x14

nonmatching D_008B01C0, 0x14

dlabel D_008B01C0
    /* 008B01C0 */ .space 0x14

nonmatching D_008B01D4, 0x14

dlabel D_008B01D4
    /* 008B01D4 */ .space 0x14

nonmatching D_008B01E8, 0x5822

dlabel D_008B01E8
    /* 008B01E8 */ .space 0x5822

nonmatching D_008B5A0A, 0xA5F6

dlabel D_008B5A0A
    /* 008B5A0A */ .space 0xA5F6

nonmatching D_008C0000, 0x46

dlabel D_008C0000
    /* 008C0000 */ .space 0x46

nonmatching D_008C0046, 0xFFBA

dlabel D_008C0046
    /* 008C0046 */ .space 0xFFBA

nonmatching D_008D0000, 0x8D

dlabel D_008D0000
    /* 008D0000 */ .space 0x8D

nonmatching D_008D008D, 0x3

dlabel D_008D008D
    /* 008D008D */ .space 0x03

nonmatching D_008D0090, 0x270

dlabel D_008D0090
    /* 008D0090 */ .space 0x270

nonmatching D_008D0300, 0x40

dlabel D_008D0300
    /* 008D0300 */ .space 0x40

nonmatching D_008D0340, 0x40

dlabel D_008D0340
    /* 008D0340 */ .space 0x40

nonmatching D_008D0380, 0x40

dlabel D_008D0380
    /* 008D0380 */ .space 0x40

nonmatching D_008D03C0, 0x5948

dlabel D_008D03C0
    /* 008D03C0 */ .space 0x5948

nonmatching D_008D5D08, 0x1A411

dlabel D_008D5D08
    /* 008D5D08 */ .space 0x1A411

nonmatching D_008F0119, 0x12

dlabel D_008F0119
    /* 008F0119 */ .space 0x12

nonmatching D_008F012B, 0x12

dlabel D_008F012B
    /* 008F012B */ .space 0x12

nonmatching D_008F013D, 0x12

dlabel D_008F013D
    /* 008F013D */ .space 0x12

nonmatching D_008F014F, 0x12

dlabel D_008F014F
    /* 008F014F */ .space 0x12

nonmatching D_008F0161, 0x16

dlabel D_008F0161
    /* 008F0161 */ .space 0x16

nonmatching D_008F0177, 0x16

dlabel D_008F0177
    /* 008F0177 */ .space 0x16

nonmatching D_008F018D, 0x16

dlabel D_008F018D
    /* 008F018D */ .space 0x16

nonmatching D_008F01A3, 0xC05D

dlabel D_008F01A3
    /* 008F01A3 */ .space 0xC05D

nonmatching WindowImage, 0x3E00

dlabel WindowImage
    /* 008FC200 */ .space 0x3E00

nonmatching D_00900000, 0x8D

dlabel D_00900000
    /* 00900000 */ .space 0x8D

nonmatching D_0090008D, 0x3

dlabel D_0090008D
    /* 0090008D */ .space 0x03

nonmatching D_00900090, 0xF9A

dlabel D_00900090
    /* 00900090 */ .space 0xF9A

nonmatching D_0090102A, 0x800

dlabel D_0090102A
    /* 0090102A */ .space 0x800

nonmatching D_0090182A, 0x14934

dlabel D_0090182A
    /* 0090182A */ .space 0x14934

nonmatching D_0091615E, 0xAEBA

dlabel D_0091615E
    /* 0091615E */ .space 0xAEBA

nonmatching D_00921018, 0xF0EF

dlabel D_00921018
    /* 00921018 */ .space 0xF0EF

nonmatching D_00930107, 0xC8F9

dlabel D_00930107
    /* 00930107 */ .space 0xC8F9

nonmatching PadDmaBuffer, 0x200

dlabel PadDmaBuffer
    /* 0093CA00 */ .space 0x200

nonmatching LW, 0x4

dlabel LW
    /* 0093CC00 */ .space 0x04

nonmatching D_0093CC04, 0x2C

dlabel D_0093CC04
    /* 0093CC04 */ .space 0x2C

nonmatching D_0093CC30, 0x2

dlabel D_0093CC30
    /* 0093CC30 */ .space 0x02

nonmatching D_0093CC32, 0x2

dlabel D_0093CC32
    /* 0093CC32 */ .space 0x02

nonmatching D_0093CC34, 0x100C

dlabel D_0093CC34
    /* 0093CC34 */ .space 0x100C

nonmatching ArcHeader, 0x4

dlabel ArcHeader
    /* 0093DC40 */ .space 0x04

nonmatching D_0093DC44, 0x14

dlabel D_0093DC44
    /* 0093DC44 */ .space 0x14

nonmatching D_0093DC58, 0x18

dlabel D_0093DC58
    /* 0093DC58 */ .space 0x18

nonmatching D_0093DC70, 0x30

dlabel D_0093DC70
    /* 0093DC70 */ .space 0x30

nonmatching queue, 0x400

dlabel queue
    /* 0093DCA0 */ .space 0x400

nonmatching mw, 0x1

dlabel mw
    /* 0093E0A0 */ .space 0x01

nonmatching D_0093E0A1, 0x3

dlabel D_0093E0A1
    /* 0093E0A1 */ .space 0x03

nonmatching D_0093E0A4, 0x1C

dlabel D_0093E0A4
    /* 0093E0A4 */ .space 0x1C

nonmatching D_0093E0C0, 0x60

dlabel D_0093E0C0
    /* 0093E0C0 */ .space 0x60

nonmatching D_0093E120, 0x24

dlabel D_0093E120
    /* 0093E120 */ .space 0x24

nonmatching D_0093E144, 0xBC

dlabel D_0093E144
    /* 0093E144 */ .space 0xBC

nonmatching StreamBuffer, 0x4000

dlabel StreamBuffer
    /* 0093E200 */ .space 0x4000

nonmatching asPacketSource, 0x28

dlabel asPacketSource
    /* 00942200 */ .space 0x28

nonmatching D_00942228, 0x28

dlabel D_00942228
    /* 00942228 */ .space 0x28

nonmatching asStudioSource, 0xF0

dlabel asStudioSource
    /* 00942250 */ .space 0xF0

nonmatching D_00942340, 0xC0D0

dlabel D_00942340
    /* 00942340 */ .space 0xC0D0

nonmatching s_apBlock, 0x4

dlabel s_apBlock
    /* 0094E410 */ .space 0x04

nonmatching D_0094E414, 0x1CF3

dlabel D_0094E414
    /* 0094E414 */ .space 0x1CF3

nonmatching D_00950107, 0x2309

dlabel D_00950107
    /* 00950107 */ .space 0x2309

nonmatching s_aBlockLayout, 0x2

dlabel s_aBlockLayout
    /* 00952410 */ .space 0x02

nonmatching D_00952412, 0x1FFE

dlabel D_00952412
    /* 00952412 */ .space 0x1FFE

nonmatching s_aBPsave, 0x400

dlabel s_aBPsave
    /* 00954410 */ .space 0x400

nonmatching s_aBLsave, 0x200

dlabel s_aBLsave
    /* 00954810 */ .space 0x200

nonmatching s_apBlockLast, 0x80

dlabel s_apBlockLast
    /* 00954A10 */ .space 0x80

nonmatching s_aBlockLayoutLast, 0x40

dlabel s_aBlockLayoutLast
    /* 00954A90 */ .space 0x40

nonmatching s_inMulColor, 0x10

dlabel s_inMulColor
    /* 00954AD0 */ .space 0x10

nonmatching s_inScale, 0x10

dlabel s_inScale
    /* 00954AE0 */ .space 0x10

nonmatching s_aDispVisible, 0x400

dlabel s_aDispVisible
    /* 00954AF0 */ .space 0x400

nonmatching s_aToumeiId, 0x40

dlabel s_aToumeiId
    /* 00954EF0 */ .space 0x40

nonmatching s_aToumei, 0x40

dlabel s_aToumei
    /* 00954F30 */ .space 0x40

nonmatching s_aShapeId, 0x80

dlabel s_aShapeId
    /* 00954F70 */ .space 0x80

nonmatching s_aShapeWeight, 0x80

dlabel s_aShapeWeight
    /* 00954FF0 */ .space 0x80

nonmatching s_aMapLast, 0x30

dlabel s_aMapLast
    /* 00955070 */ .space 0x30

nonmatching s_inShadowVec, 0x10

dlabel s_inShadowVec
    /* 009550A0 */ .space 0x10

nonmatching s_apModelLayout, 0x800

dlabel s_apModelLayout
    /* 009550B0 */ .space 0x800

nonmatching s_inGblPos, 0x10

dlabel s_inGblPos
    /* 009558B0 */ .space 0x10

nonmatching s_inGblPlace, 0x40

dlabel s_inGblPlace
    /* 009558C0 */ .space 0x40

nonmatching s_aCircleShadow, 0x1020

dlabel s_aCircleShadow
    /* 00955900 */ .space 0x1020

nonmatching s_aCircleShadowClut, 0x20

dlabel s_aCircleShadowClut
    /* 00956920 */ .space 0x20

nonmatching D_00956940, 0x1000

dlabel D_00956940
    /* 00956940 */ .space 0x1000

nonmatching s_aAlphaGroup, 0x4

dlabel s_aAlphaGroup
    /* 00957940 */ .space 0x04

nonmatching D_00957944, 0x1FF8

dlabel D_00957944
    /* 00957944 */ .space 0x1FF8

nonmatching D_0095993C, 0x4

dlabel D_0095993C
    /* 0095993C */ .space 0x04

nonmatching s_aNonAlphaGroup, 0x8

dlabel s_aNonAlphaGroup
    /* 00959940 */ .space 0x08

nonmatching D_00959948, 0x1FF8

dlabel D_00959948
    /* 00959948 */ .space 0x1FF8

nonmatching s_inProReal, 0x170

dlabel s_inProReal
    /* 0095B940 */ .space 0x170

nonmatching D_0095BAB0, 0x20

dlabel D_0095BAB0
    /* 0095BAB0 */ .space 0x20

nonmatching D_0095BAD0, 0x50

dlabel D_0095BAD0
    /* 0095BAD0 */ .space 0x50

nonmatching s_inBackBuffer, 0x1C

dlabel s_inBackBuffer
    /* 0095BB20 */ .space 0x1C

nonmatching D_0095BB3C, 0x8

dlabel D_0095BB3C
    /* 0095BB3C */ .space 0x08

nonmatching D_0095BB44, 0xC

dlabel D_0095BB44
    /* 0095BB44 */ .space 0x0C

nonmatching s_aParentBuf, 0x2000

dlabel s_aParentBuf
    /* 0095BB50 */ .space 0x2000

nonmatching s_inMapHandle, 0x10

dlabel s_inMapHandle
    /* 0095DB50 */ .space 0x10

nonmatching s_inFadeOut, 0x10

dlabel s_inFadeOut
    /* 0095DB60 */ .space 0x10

nonmatching D_0095DB70, 0x14

dlabel D_0095DB70
    /* 0095DB70 */ .space 0x14

nonmatching D_0095DB84, 0x4

dlabel D_0095DB84
    /* 0095DB84 */ .space 0x04

nonmatching D_0095DB88, 0x8

dlabel D_0095DB88
    /* 0095DB88 */ .space 0x08

nonmatching D_0095DB90, 0x10

dlabel D_0095DB90
    /* 0095DB90 */ .space 0x10

nonmatching s_inFadeIn, 0x10

dlabel s_inFadeIn
    /* 0095DBA0 */ .space 0x10

nonmatching D_0095DBB0, 0x14

dlabel D_0095DBB0
    /* 0095DBB0 */ .space 0x14

nonmatching D_0095DBC4, 0x4

dlabel D_0095DBC4
    /* 0095DBC4 */ .space 0x04

nonmatching D_0095DBC8, 0x18

dlabel D_0095DBC8
    /* 0095DBC8 */ .space 0x18

nonmatching s_inActiveFadeOut, 0x10

dlabel s_inActiveFadeOut
    /* 0095DBE0 */ .space 0x10

nonmatching D_0095DBF0, 0x18

dlabel D_0095DBF0
    /* 0095DBF0 */ .space 0x18

nonmatching D_0095DC08, 0x18

dlabel D_0095DC08
    /* 0095DC08 */ .space 0x18

nonmatching s_inActiveFadeIn, 0x10

dlabel s_inActiveFadeIn
    /* 0095DC20 */ .space 0x10

nonmatching D_0095DC30, 0x18

dlabel D_0095DC30
    /* 0095DC30 */ .space 0x18

nonmatching D_0095DC48, 0x18

dlabel D_0095DC48
    /* 0095DC48 */ .space 0x18

nonmatching s_aDirect, 0xABE0

dlabel s_aDirect
    /* 0095DC60 */ .space 0xABE0

nonmatching s_aTexName, 0x20

dlabel s_aTexName
    /* 00968840 */ .space 0x20

nonmatching s_aMatName, 0x20

dlabel s_aMatName
    /* 00968860 */ .space 0x20

nonmatching s_inGblPointP, 0x40

dlabel s_inGblPointP
    /* 00968880 */ .space 0x40

nonmatching s_inGblPointC, 0x40

dlabel s_inGblPointC
    /* 009688C0 */ .space 0x40

nonmatching s_inGblFogCol, 0x10

dlabel s_inGblFogCol
    /* 00968900 */ .space 0x10

nonmatching s_inGblFogPara, 0x10

dlabel s_inGblFogPara
    /* 00968910 */ .space 0x10

nonmatching s_inMainCameraPos, 0x10

dlabel s_inMainCameraPos
    /* 00968920 */ .space 0x10

nonmatching s_inMainCameraAng, 0x10

dlabel s_inMainCameraAng
    /* 00968930 */ .space 0x10

nonmatching s_inLc0, 0x40

dlabel s_inLc0
    /* 00968940 */ .space 0x40

nonmatching s_inCulling, 0xDE0

dlabel s_inCulling
    /* 00968980 */ .space 0xDE0

nonmatching D_00969760, 0x20

dlabel D_00969760
    /* 00969760 */ .space 0x20

nonmatching MYclientPtr, 0x68F8

dlabel MYclientPtr
    /* 00969780 */ .space 0x68F8

nonmatching D_00970078, 0x113

dlabel D_00970078
    /* 00970078 */ .space 0x113

nonmatching D_0097018B, 0x7DF

dlabel D_0097018B
    /* 0097018B */ .space 0x7DF

nonmatching D_0097096A, 0x8E56

dlabel D_0097096A
    /* 0097096A */ .space 0x8E56

nonmatching MYserverPtr, 0x681E

dlabel MYserverPtr
    /* 009797C0 */ .space 0x681E

nonmatching D_0097FFDE, 0xBA

dlabel D_0097FFDE
    /* 0097FFDE */ .space 0xBA

nonmatching D_00980098, 0x9E3

dlabel D_00980098
    /* 00980098 */ .space 0x9E3

nonmatching D_00980A7B, 0x8D65

dlabel D_00980A7B
    /* 00980A7B */ .space 0x8D65

nonmatching MYthreadStack, 0x4000

dlabel MYthreadStack
    /* 009897E0 */ .space 0x4000

nonmatching MYwaveTransThStack, 0x313F

dlabel MYwaveTransThStack
    /* 0098D7E0 */ .space 0x313F

nonmatching D_0099091F, 0x15F

dlabel D_0099091F
    /* 0099091F */ .space 0x15F

nonmatching D_00990A7E, 0xD82

dlabel D_00990A7E
    /* 00990A7E */ .space 0xD82

nonmatching _pckt_buffer, 0x80

dlabel _pckt_buffer
    /* 00991800 */ .space 0x80

nonmatching _send_buffer, 0x40

dlabel _send_buffer
    /* 00991880 */ .space 0x40

nonmatching _csdata, 0x14

dlabel _csdata
    /* 009918C0 */ .space 0x14

nonmatching sif0_handleid, 0x4

dlabel sif0_handleid
    /* 009918D4 */ .space 0x04

nonmatching _data_table_009918D8, 0x8

dlabel _data_table_009918D8
    /* 009918D8 */ .space 0x08

nonmatching D_009918E0, 0x4

dlabel D_009918E0
    /* 009918E0 */ .space 0x04

nonmatching D_009918E4, 0x8

dlabel D_009918E4
    /* 009918E4 */ .space 0x08

nonmatching D_009918EC, 0x14

dlabel D_009918EC
    /* 009918EC */ .space 0x14

nonmatching _sys_buffer, 0x100

dlabel _sys_buffer
    /* 00991900 */ .space 0x100

nonmatching soft_reg, 0x80

dlabel soft_reg
    /* 00991A00 */ .space 0x80

nonmatching _packet_buffer, 0x800

dlabel _packet_buffer
    /* 00991A80 */ .space 0x800

nonmatching _free_buffer, 0x800

dlabel _free_buffer
    /* 00992280 */ .space 0x800

nonmatching _free_buffer2, 0x800

dlabel _free_buffer2
    /* 00992A80 */ .space 0x800

nonmatching _data_table_00993280, 0x40

dlabel _data_table_00993280
    /* 00993280 */ .space 0x40

nonmatching rcv_adr.30, 0x4

dlabel rcv_adr.30
    /* 009932C0 */ .space 0x04

nonmatching ip0.55, 0x3C

dlabel ip0.55
    /* 009932C4 */ .space 0x3C

nonmatching _send_data, 0xC40

dlabel _send_data
    /* 00993300 */ .space 0xC40

nonmatching _rcv_data_rpc, 0x40

dlabel _rcv_data_rpc
    /* 00993F40 */ .space 0x40

nonmatching _rcv_data_cmd, 0x10

dlabel _rcv_data_cmd
    /* 00993F80 */ .space 0x10

nonmatching D_00993F90, 0x4

dlabel D_00993F90
    /* 00993F90 */ .space 0x04

nonmatching D_00993F94, 0x42C

dlabel D_00993F94
    /* 00993F94 */ .space 0x42C

nonmatching _iob, 0x200

dlabel _iob
    /* 009943C0 */ .space 0x200

nonmatching _cd, 0x28

dlabel _cd
    /* 009945C0 */ .space 0x28

nonmatching _fsversion, 0x18

dlabel _fsversion
    /* 009945E8 */ .space 0x18

nonmatching _sif_FsRcv_Data, 0x40

dlabel _sif_FsRcv_Data
    /* 00994600 */ .space 0x40

nonmatching _sif_FsPoff_Data, 0x40

dlabel _sif_FsPoff_Data
    /* 00994640 */ .space 0x40

nonmatching cd_00994680, 0x40

dlabel cd_00994680
    /* 00994680 */ .space 0x40

nonmatching rdata_009946C0, 0x40

dlabel rdata_009946C0
    /* 009946C0 */ .space 0x40

nonmatching sdata, 0x40

dlabel sdata
    /* 00994700 */ .space 0x40

nonmatching _lih_data, 0x100

dlabel _lih_data
    /* 00994740 */ .space 0x100

nonmatching _senddata, 0x8

dlabel _senddata
    /* 00994840 */ .space 0x08

nonmatching D_00994848, 0x1F8

dlabel D_00994848
    /* 00994848 */ .space 0x1F8

nonmatching cd_00994A40, 0x28

dlabel cd_00994A40
    /* 00994A40 */ .space 0x28

nonmatching _lfversion, 0x18

dlabel _lfversion
    /* 00994A68 */ .space 0x18

nonmatching rdata_00994A80, 0x70

dlabel rdata_00994A80
    /* 00994A80 */ .space 0x70

nonmatching stack.6, 0x400

dlabel stack.6
    /* 00994AF0 */ .space 0x400

nonmatching topSema, 0x8

dlabel topSema
    /* 00994EF0 */ .space 0x08

nonmatching topArg, 0x408

dlabel topArg
    /* 00994EF8 */ .space 0x408

nonmatching q.3, 0x110

dlabel q.3
    /* 00995300 */ .space 0x110

nonmatching tinfo, 0x18

dlabel tinfo
    /* 00995410 */ .space 0x18

nonmatching D_00995428, 0x18

dlabel D_00995428
    /* 00995428 */ .space 0x18

nonmatching wbuf, 0x140

dlabel wbuf
    /* 00995440 */ .space 0x140

nonmatching rbuf, 0x140

dlabel rbuf
    /* 00995580 */ .space 0x140

nonmatching linebuf, 0x1080

dlabel linebuf
    /* 009956C0 */ .space 0x1080

nonmatching EER00, 0x10

dlabel EER00
    /* 00996740 */ .space 0x10

nonmatching EERAT, 0x10

dlabel EERAT
    /* 00996750 */ .space 0x10

nonmatching EERV0, 0x10

dlabel EERV0
    /* 00996760 */ .space 0x10

nonmatching EERV1, 0x10

dlabel EERV1
    /* 00996770 */ .space 0x10

nonmatching EER04, 0x10

dlabel EER04
    /* 00996780 */ .space 0x10

nonmatching EER05, 0x10

dlabel EER05
    /* 00996790 */ .space 0x10

nonmatching EER06, 0x10

dlabel EER06
    /* 009967A0 */ .space 0x10

nonmatching EER07, 0x10

dlabel EER07
    /* 009967B0 */ .space 0x10

nonmatching EER08, 0x10

dlabel EER08
    /* 009967C0 */ .space 0x10

nonmatching EER09, 0x10

dlabel EER09
    /* 009967D0 */ .space 0x10

nonmatching EER10, 0x10

dlabel EER10
    /* 009967E0 */ .space 0x10

nonmatching EER11, 0x10

dlabel EER11
    /* 009967F0 */ .space 0x10

nonmatching EER12, 0x10

dlabel EER12
    /* 00996800 */ .space 0x10

nonmatching EER13, 0x10

dlabel EER13
    /* 00996810 */ .space 0x10

nonmatching EER14, 0x10

dlabel EER14
    /* 00996820 */ .space 0x10

nonmatching EER15, 0x10

dlabel EER15
    /* 00996830 */ .space 0x10

nonmatching EER16, 0x10

dlabel EER16
    /* 00996840 */ .space 0x10

nonmatching EER17, 0x10

dlabel EER17
    /* 00996850 */ .space 0x10

nonmatching EER18, 0x10

dlabel EER18
    /* 00996860 */ .space 0x10

nonmatching EER19, 0x10

dlabel EER19
    /* 00996870 */ .space 0x10

nonmatching EER20, 0x10

dlabel EER20
    /* 00996880 */ .space 0x10

nonmatching EER21, 0x10

dlabel EER21
    /* 00996890 */ .space 0x10

nonmatching EER22, 0x10

dlabel EER22
    /* 009968A0 */ .space 0x10

nonmatching EER23, 0x10

dlabel EER23
    /* 009968B0 */ .space 0x10

nonmatching EER24, 0x10

dlabel EER24
    /* 009968C0 */ .space 0x10

nonmatching EER25, 0x10

dlabel EER25
    /* 009968D0 */ .space 0x10

nonmatching EER26, 0x10

dlabel EER26
    /* 009968E0 */ .space 0x10

nonmatching EER27, 0x10

dlabel EER27
    /* 009968F0 */ .space 0x10

nonmatching EERGP, 0x10

dlabel EERGP
    /* 00996900 */ .space 0x10

nonmatching EERSP, 0x10

dlabel EERSP
    /* 00996910 */ .space 0x10

nonmatching EERFP, 0x10

dlabel EERFP
    /* 00996920 */ .space 0x10

nonmatching EERRA, 0x10

dlabel EERRA
    /* 00996930 */ .space 0x10

nonmatching EERH0, 0x8

dlabel EERH0
    /* 00996940 */ .space 0x08

nonmatching EERH1, 0x8

dlabel EERH1
    /* 00996948 */ .space 0x08

nonmatching EERL0, 0x8

dlabel EERL0
    /* 00996950 */ .space 0x08

nonmatching EERL1, 0x8

dlabel EERL1
    /* 00996958 */ .space 0x08

nonmatching EERSA, 0x8

dlabel EERSA
    /* 00996960 */ .space 0x08

nonmatching EEEPC, 0x8

dlabel EEEPC
    /* 00996968 */ .space 0x08

nonmatching userarea, 0x50

dlabel userarea
    /* 00996970 */ .space 0x50

nonmatching padsif, 0x50

dlabel padsif
    /* 009969C0 */ .space 0x50

nonmatching PadInfo, 0xF0

dlabel PadInfo
    /* 00996A10 */ .space 0xF0

nonmatching dma_iop_data, 0x100

dlabel dma_iop_data
    /* 00996B00 */ .space 0x100

nonmatching buffer_00996C00, 0x80

dlabel buffer_00996C00
    /* 00996C00 */ .space 0x80

nonmatching sceCdCbfunc, 0x4

dlabel sceCdCbfunc
    /* 00996C80 */ .space 0x04

nonmatching sceCdPoffCbfunc, 0x4

dlabel sceCdPoffCbfunc
    /* 00996C84 */ .space 0x04

nonmatching sceCdPoffCbdata, 0x4

dlabel sceCdPoffCbdata
    /* 00996C88 */ .space 0x04

nonmatching sceCdPoffCbfunc_num, 0x4

dlabel sceCdPoffCbfunc_num
    /* 00996C8C */ .space 0x04

nonmatching my_thid, 0x8

dlabel my_thid
    /* 00996C90 */ .space 0x08

nonmatching my_th_info, 0x30

dlabel my_th_info
    /* 00996C98 */ .space 0x30

nonmatching cb_tp, 0x38

dlabel cb_tp
    /* 00996CC8 */ .space 0x38

nonmatching _sf_data, 0x24

dlabel _sf_data
    /* 00996D00 */ .space 0x24

nonmatching D_00996D24, 0x11C

dlabel D_00996D24
    /* 00996D24 */ .space 0x11C

nonmatching sfrdata, 0x40

dlabel sfrdata
    /* 00996E40 */ .space 0x40

nonmatching cdrdsf, 0x28

dlabel cdrdsf
    /* 00996E80 */ .space 0x28

nonmatching cdit, 0x28

dlabel cdit
    /* 00996EA8 */ .space 0x28

nonmatching cddr, 0x30

dlabel cddr
    /* 00996ED0 */ .space 0x30

nonmatching _i_mode, 0x10

dlabel _i_mode
    /* 00996F00 */ .space 0x10

nonmatching _dr_mode, 0x8

dlabel _dr_mode
    /* 00996F10 */ .space 0x08

nonmatching dum_mode, 0x28

dlabel dum_mode
    /* 00996F18 */ .space 0x28

nonmatching mcClientID, 0x28

dlabel mcClientID
    /* 00996F40 */ .space 0x28

nonmatching typeAddr, 0x4

dlabel typeAddr
    /* 00996F68 */ .space 0x04

nonmatching freeAddr, 0x4

dlabel freeAddr
    /* 00996F6C */ .space 0x04

nonmatching formAddr, 0x10

dlabel formAddr
    /* 00996F70 */ .space 0x10

nonmatching buffFileInfo, 0x20

dlabel buffFileInfo
    /* 00996F80 */ .space 0x20

nonmatching D_00996FA0, 0x20

dlabel D_00996FA0
    /* 00996FA0 */ .space 0x20

nonmatching sifParamOrd, 0x30

dlabel sifParamOrd
    /* 00996FC0 */ .space 0x30

nonmatching sifParamFname, 0x14

dlabel sifParamFname
    /* 00996FF0 */ .space 0x14

nonmatching D_00997004, 0x43C

dlabel D_00997004
    /* 00997004 */ .space 0x43C

nonmatching sifParamNext, 0xC0

dlabel sifParamNext
    /* 00997440 */ .space 0xC0

nonmatching currentDir, 0x1000

dlabel currentDir
    /* 00997500 */ .space 0x1000

nonmatching retval, 0x40

dlabel retval
    /* 00998500 */ .space 0x40

nonmatching _sprtagdata.24, 0x200

dlabel _sprtagdata.24
    /* 00998540 */ .space 0x200

nonmatching object.2, 0x18

dlabel object.2
    /* 00998740 */ .space 0x18

nonmatching initialized.3, 0x4

dlabel initialized.3
    /* 00998758 */ .space 0x04

nonmatching marker.0, 0x4

dlabel marker.0
    /* 0099875C */ .space 0x04

nonmatching objects, 0x8

dlabel objects
    /* 00998760 */ .space 0x08

nonmatching msg_buffer, 0x4088

dlabel msg_buffer
    /* 00998768 */ .space 0x4088

nonmatching cursor, 0x4

dlabel cursor
    /* 0099C7F0 */ .space 0x04

nonmatching D_0099C7F4, 0xC

dlabel D_0099C7F4
    /* 0099C7F4 */ .space 0x0C

nonmatching D_0099C800, 0x50

dlabel D_0099C800
    /* 0099C800 */ .space 0x50

nonmatching playControl, 0x1E0

dlabel playControl
    /* 0099C850 */ .space 0x1E0

nonmatching ewComponent, 0xA00

dlabel ewComponent
    /* 0099CA30 */ .space 0xA00

nonmatching classDB, 0x20

dlabel classDB
    /* 0099D430 */ .space 0x20

nonmatching VMRegister, 0x80

dlabel VMRegister
    /* 0099D450 */ .space 0x80

nonmatching primitiveClassTable, 0x40

dlabel primitiveClassTable
    /* 0099D4D0 */ .space 0x40

nonmatching key_value, 0x400

dlabel key_value
    /* 0099D510 */ .space 0x400

nonmatching D_0099D910, 0xA94

dlabel D_0099D910
    /* 0099D910 */ .space 0xA94
