.include "macro.inc"

.section .sbss, "wa"

/* Generated by spimdisasm 1.40.0 */

nonmatching _fbss, 0x4

dlabel _fbss
    /* 004DC500 */ .space 0x04

nonmatching shopNo, 0x4

dlabel shopNo
    /* 004DC504 */ .space 0x04

nonmatching GameCFSoundMenuPurgeFlag, 0x8

dlabel GameCFSoundMenuPurgeFlag
    /* 004DC508 */ .space 0x08

nonmatching attrPrev, 0x8

dlabel attrPrev
    /* 004DC510 */ .space 0x08

nonmatching prevTouch, 0x4

dlabel prevTouch
    /* 004DC518 */ .space 0x04

nonmatching pa.0, 0x4

dlabel pa.0
    /* 004DC51C */ .space 0x04

nonmatching t.1, 0x4

dlabel t.1
    /* 004DC520 */ .space 0x04

nonmatching pre_mode, 0x4

dlabel pre_mode
    /* 004DC524 */ .space 0x04

nonmatching WALK_THRESHOLD_I, 0x4

dlabel WALK_THRESHOLD_I
    /* 004DC528 */ .space 0x04

nonmatching WALK_THRESHOLD_F, 0x4

dlabel WALK_THRESHOLD_F
    /* 004DC52C */ .space 0x04

nonmatching RUN_THRESHOLD_I, 0x4

dlabel RUN_THRESHOLD_I
    /* 004DC530 */ .space 0x04

nonmatching RUN_THRESHOLD_F, 0x4

dlabel RUN_THRESHOLD_F
    /* 004DC534 */ .space 0x04

nonmatching VECTOR_RATE, 0x4

dlabel VECTOR_RATE
    /* 004DC538 */ .space 0x04

nonmatching GameCfPlayerLoadResource_preCID, 0x2

dlabel GameCfPlayerLoadResource_preCID
    /* 004DC53C */ .space 0x02

nonmatching GameCfPlayerLoadResource_preCurry, 0x2

dlabel GameCfPlayerLoadResource_preCurry
    /* 004DC53E */ .space 0x02

nonmatching arcfileaddr, 0x4

dlabel arcfileaddr
    /* 004DC540 */ .space 0x04

nonmatching arcno, 0x4

dlabel arcno
    /* 004DC544 */ .space 0x04

nonmatching arcfilepreload, 0x4

dlabel arcfilepreload
    /* 004DC548 */ .space 0x04

nonmatching GameResourceWorkReloadLeader, 0x4

dlabel GameResourceWorkReloadLeader
    /* 004DC54C */ .space 0x04

nonmatching cnt.2, 0x4

dlabel cnt.2
    /* 004DC550 */ .space 0x04

nonmatching image_004DC554, 0x4

dlabel image_004DC554
    /* 004DC554 */ .space 0x04

nonmatching rate, 0x1

dlabel rate
    /* 004DC558 */ .space 0x01

nonmatching ping, 0x3

dlabel ping
    /* 004DC559 */ .space 0x03

nonmatching flag.0, 0x4

dlabel flag.0
    /* 004DC55C */ .space 0x04

nonmatching pnum, 0x4

dlabel pnum
    /* 004DC560 */ .space 0x04

nonmatching pext, 0x4

dlabel pext
    /* 004DC564 */ .space 0x04

nonmatching cascade, 0x4

dlabel cascade
    /* 004DC568 */ .space 0x04

nonmatching TmpBuffer, 0x4

dlabel TmpBuffer
    /* 004DC56C */ .space 0x04

nonmatching layer, 0x2

dlabel layer
    /* 004DC570 */ .space 0x02

nonmatching zpicf, 0x2

dlabel zpicf
    /* 004DC572 */ .space 0x02

nonmatching alpha, 0x4

dlabel alpha
    /* 004DC574 */ .space 0x04

nonmatching transparency, 0x4

dlabel transparency
    /* 004DC578 */ .space 0x04

nonmatching rubyX1, 0x4

dlabel rubyX1
    /* 004DC57C */ .space 0x04

nonmatching rubyX2, 0x4

dlabel rubyX2
    /* 004DC580 */ .space 0x04

nonmatching rubyY, 0x4

dlabel rubyY
    /* 004DC584 */ .space 0x04

nonmatching cnvCW, 0x4

dlabel cnvCW
    /* 004DC588 */ .space 0x04

nonmatching cnvCH, 0x4

dlabel cnvCH
    /* 004DC58C */ .space 0x04

nonmatching groupStatus, 0x3

dlabel groupStatus
    /* 004DC590 */ .space 0x03

nonmatching D_004DC593, 0x1

dlabel D_004DC593
    /* 004DC593 */ .space 0x01

nonmatching currentScriptDB, 0x4

dlabel currentScriptDB
    /* 004DC594 */ .space 0x04

nonmatching fileSelect, 0x4

dlabel fileSelect
    /* 004DC598 */ .space 0x04

nonmatching heapUsed, 0x4

dlabel heapUsed
    /* 004DC59C */ .space 0x04

nonmatching lightFileNum, 0x4

dlabel lightFileNum
    /* 004DC5A0 */ .space 0x04

nonmatching resourceID, 0x4

dlabel resourceID
    /* 004DC5A4 */ .space 0x04

nonmatching mode_004DC5A8, 0x4

dlabel mode_004DC5A8
    /* 004DC5A8 */ .space 0x04

nonmatching toolFlags, 0x4

dlabel toolFlags
    /* 004DC5AC */ .space 0x04

nonmatching partsIndex, 0x4

dlabel partsIndex
    /* 004DC5B0 */ .space 0x04

nonmatching lightIndex, 0x4

dlabel lightIndex
    /* 004DC5B4 */ .space 0x04

nonmatching tokenCurrent, 0x4

dlabel tokenCurrent
    /* 004DC5B8 */ .space 0x04

nonmatching tokenLimit, 0x4

dlabel tokenLimit
    /* 004DC5BC */ .space 0x04

nonmatching tokenType, 0x4

dlabel tokenType
    /* 004DC5C0 */ .space 0x04

nonmatching size.68, 0x4

dlabel size.68
    /* 004DC5C4 */ .space 0x04

nonmatching buffer.72, 0x4

dlabel buffer.72
    /* 004DC5C8 */ .space 0x04

nonmatching original_font_no.1, 0x4

dlabel original_font_no.1
    /* 004DC5CC */ .space 0x04

nonmatching MenuTopCommandLock, 0x4

dlabel MenuTopCommandLock
    /* 004DC5D0 */ .space 0x04

nonmatching MessageCpyEnd, 0x4

dlabel MessageCpyEnd
    /* 004DC5D4 */ .space 0x04

nonmatching pPrintFuncTop, 0x8

dlabel pPrintFuncTop
    /* 004DC5D8 */ .space 0x08

nonmatching msg03.3, 0x5

dlabel msg03.3
    /* 004DC5E0 */ .space 0x05

nonmatching D_004DC5E5, 0x3

dlabel D_004DC5E5
    /* 004DC5E5 */ .space 0x03

nonmatching MenuCharPartyReser, 0x8

dlabel MenuCharPartyReser
    /* 004DC5E8 */ .space 0x08

nonmatching CharWinSP, 0x8

dlabel CharWinSP
    /* 004DC5F0 */ .space 0x08

nonmatching MenuShopWork, 0x4

dlabel MenuShopWork
    /* 004DC5F8 */ .space 0x04

nonmatching MenuShopTask, 0x4

dlabel MenuShopTask
    /* 004DC5FC */ .space 0x04

nonmatching MenuShopWinSP, 0x4

dlabel MenuShopWinSP
    /* 004DC600 */ .space 0x04

nonmatching ShopDataBufTop, 0x4

dlabel ShopDataBufTop
    /* 004DC604 */ .space 0x04

nonmatching tActor, 0x4

dlabel tActor
    /* 004DC608 */ .space 0x04

nonmatching pDrillFlag, 0x4

dlabel pDrillFlag
    /* 004DC60C */ .space 0x04

nonmatching wtype, 0x4

dlabel wtype
    /* 004DC610 */ .space 0x04

nonmatching pCamera_004DC614, 0x4

dlabel pCamera_004DC614
    /* 004DC614 */ .space 0x04

nonmatching crx_004DC618, 0x4

dlabel crx_004DC618
    /* 004DC618 */ .space 0x04

nonmatching cry_004DC61C, 0x4

dlabel cry_004DC61C
    /* 004DC61C */ .space 0x04

nonmatching crvx, 0x4

dlabel crvx
    /* 004DC620 */ .space 0x04

nonmatching crvy, 0x4

dlabel crvy
    /* 004DC624 */ .space 0x04

nonmatching wpow, 0x4

dlabel wpow
    /* 004DC628 */ .space 0x04

nonmatching pAct_004DC62C, 0x4

dlabel pAct_004DC62C
    /* 004DC62C */ .space 0x04

nonmatching shake, 0x4

dlabel shake
    /* 004DC630 */ .space 0x04

nonmatching pCamera_004DC634, 0x4

dlabel pCamera_004DC634
    /* 004DC634 */ .space 0x04

nonmatching pAct_004DC638, 0x4

dlabel pAct_004DC638
    /* 004DC638 */ .space 0x04

nonmatching listpos, 0x4

dlabel listpos
    /* 004DC63C */ .space 0x04

nonmatching listnum, 0x4

dlabel listnum
    /* 004DC640 */ .space 0x04

nonmatching mot, 0x4

dlabel mot
    /* 004DC644 */ .space 0x04

nonmatching listnow, 0x4

dlabel listnow
    /* 004DC648 */ .space 0x04

nonmatching lookY, 0x4

dlabel lookY
    /* 004DC64C */ .space 0x04

nonmatching crx_004DC650, 0x4

dlabel crx_004DC650
    /* 004DC650 */ .space 0x04

nonmatching cry_004DC654, 0x4

dlabel cry_004DC654
    /* 004DC654 */ .space 0x04

nonmatching pause, 0x4

dlabel pause
    /* 004DC658 */ .space 0x04

nonmatching pCamera_004DC65C, 0x4

dlabel pCamera_004DC65C
    /* 004DC65C */ .space 0x04

nonmatching radius, 0x4

dlabel radius
    /* 004DC660 */ .space 0x04

nonmatching charID.3, 0x4

dlabel charID.3
    /* 004DC664 */ .space 0x04

nonmatching eftCate.4, 0x4

dlabel eftCate.4
    /* 004DC668 */ .space 0x04

nonmatching _nowImage, 0x4

dlabel _nowImage
    /* 004DC66C */ .space 0x04

nonmatching _nowScheduler, 0x4

dlabel _nowScheduler
    /* 004DC670 */ .space 0x04

nonmatching _nowScriptAdr, 0x4

dlabel _nowScriptAdr
    /* 004DC674 */ .space 0x04

nonmatching _nowParentLocal, 0x8

dlabel _nowParentLocal
    /* 004DC678 */ .space 0x08

nonmatching _sefLoadEftQue, 0x4

dlabel _sefLoadEftQue
    /* 004DC680 */ .space 0x04

nonmatching _nRead, 0x4

dlabel _nRead
    /* 004DC684 */ .space 0x04

nonmatching charID.0, 0x4

dlabel charID.0
    /* 004DC688 */ .space 0x04

nonmatching eftCate.1, 0x4

dlabel eftCate.1
    /* 004DC68C */ .space 0x04

nonmatching pmcHead, 0x4

dlabel pmcHead
    /* 004DC690 */ .space 0x04

nonmatching nMemCell, 0x4

dlabel nMemCell
    /* 004DC694 */ .space 0x04

nonmatching heap_top, 0x4

dlabel heap_top
    /* 004DC698 */ .space 0x04

nonmatching heap_size, 0x4

dlabel heap_size
    /* 004DC69C */ .space 0x04

nonmatching frame_stack, 0x4

dlabel frame_stack
    /* 004DC6A0 */ .space 0x04

nonmatching freeBlock, 0x4

dlabel freeBlock
    /* 004DC6A4 */ .space 0x04

nonmatching args_jump, 0x8

dlabel args_jump
    /* 004DC6A8 */ .space 0x08

nonmatching defaultLayout, 0x4

dlabel defaultLayout
    /* 004DC6B0 */ .space 0x04

nonmatching D_004DC6B4, 0x4

dlabel D_004DC6B4
    /* 004DC6B4 */ .space 0x04

nonmatching iCurrentThread, 0x4

dlabel iCurrentThread
    /* 004DC6B8 */ .space 0x04

nonmatching iRotateSignal, 0x4

dlabel iRotateSignal
    /* 004DC6BC */ .space 0x04

nonmatching mfifo_drain, 0x8

dlabel mfifo_drain
    /* 004DC6C0 */ .space 0x08

nonmatching callback, 0x4

dlabel callback
    /* 004DC6C8 */ .space 0x04

nonmatching ReadClockInterval, 0x4

dlabel ReadClockInterval
    /* 004DC6CC */ .space 0x04

nonmatching PresentTime, 0x7

dlabel PresentTime
    /* 004DC6D0 */ .space 0x07

nonmatching D_004DC6D7, 0x1

dlabel D_004DC6D7
    /* 004DC6D7 */ .space 0x01

nonmatching StrList, 0x4

dlabel StrList
    /* 004DC6D8 */ .space 0x04

nonmatching loaded_overlay, 0x1

dlabel loaded_overlay
    /* 004DC6DC */ .space 0x01

nonmatching queue_top, 0x1

dlabel queue_top
    /* 004DC6DD */ .space 0x01

nonmatching queue_end, 0x1

dlabel queue_end
    /* 004DC6DE */ .space 0x01

nonmatching count.3_004DC6DF, 0x1

dlabel count.3_004DC6DF
    /* 004DC6DF */ .space 0x01

nonmatching HddActive, 0x4

dlabel HddActive
    /* 004DC6E0 */ .space 0x04

nonmatching CurrentColiHead, 0x4

dlabel CurrentColiHead
    /* 004DC6E4 */ .space 0x04

nonmatching iRandSeed, 0x8

dlabel iRandSeed
    /* 004DC6E8 */ .space 0x08

nonmatching pCurrentPacket, 0x4

dlabel pCurrentPacket
    /* 004DC6F0 */ .space 0x04

nonmatching pSendPacket, 0x4

dlabel pSendPacket
    /* 004DC6F4 */ .space 0x04

nonmatching pCurrentStudio, 0x8

dlabel pCurrentStudio
    /* 004DC6F8 */ .space 0x08

nonmatching s_aTexOffset, 0x8

dlabel s_aTexOffset
    /* 004DC700 */ .space 0x08

nonmatching s_nAlphaGroup, 0x4

dlabel s_nAlphaGroup
    /* 004DC708 */ .space 0x04

nonmatching s_nNonAlphaGroup, 0x4

dlabel s_nNonAlphaGroup
    /* 004DC70C */ .space 0x04

nonmatching defaultVM, 0x4

dlabel defaultVM
    /* 004DC710 */ .space 0x04

nonmatching rcFile, 0x4

dlabel rcFile
    /* 004DC714 */ .space 0x04

nonmatching UseVMFlag, 0x4

dlabel UseVMFlag
    /* 004DC718 */ .space 0x04

nonmatching stageVM, 0x4

dlabel stageVM
    /* 004DC71C */ .space 0x04

nonmatching evtVM, 0x8

dlabel evtVM
    /* 004DC720 */ .space 0x08

nonmatching cursorMode, 0x4

dlabel cursorMode
    /* 004DC728 */ .space 0x04

nonmatching primitive, 0x4

dlabel primitive
    /* 004DC72C */ .space 0x04

nonmatching numClass, 0x4

dlabel numClass
    /* 004DC730 */ .space 0x04

nonmatching classes, 0x4

dlabel classes
    /* 004DC734 */ .space 0x04

nonmatching numPrimitive, 0x8

dlabel numPrimitive
    /* 004DC738 */ .space 0x08

nonmatching ATTR_InnerClasses, 0x4

dlabel ATTR_InnerClasses
    /* 004DC740 */ .space 0x04

nonmatching ATTR_LocalVariableTable, 0x4

dlabel ATTR_LocalVariableTable
    /* 004DC744 */ .space 0x04

nonmatching ATTR_ConstantValue, 0x4

dlabel ATTR_ConstantValue
    /* 004DC748 */ .space 0x04

nonmatching ATTR_LineNumberTable, 0x4

dlabel ATTR_LineNumberTable
    /* 004DC74C */ .space 0x04

nonmatching XTK_peerGroup, 0x2

dlabel XTK_peerGroup
    /* 004DC750 */ .space 0x02

nonmatching D_004DC752, 0x4

dlabel D_004DC752
    /* 004DC752 */ .space 0x04

nonmatching D_004DC756, 0x2

dlabel D_004DC756
    /* 004DC756 */ .space 0x02

nonmatching classStringBuffer, 0x4

dlabel classStringBuffer
    /* 004DC758 */ .space 0x04

nonmatching TYPE_Chr_talk, 0x4

dlabel TYPE_Chr_talk
    /* 004DC75C */ .space 0x04

nonmatching ATTR_SourceFile, 0x4

dlabel ATTR_SourceFile
    /* 004DC760 */ .space 0x04

nonmatching ATTR_Code, 0x4

dlabel ATTR_Code
    /* 004DC764 */ .space 0x04

nonmatching TYPE_Void, 0x4

dlabel TYPE_Void
    /* 004DC768 */ .space 0x04

nonmatching NAME_Constructor, 0x4

dlabel NAME_Constructor
    /* 004DC76C */ .space 0x04

nonmatching ATTR_Exceptions, 0x4

dlabel ATTR_Exceptions
    /* 004DC770 */ .space 0x04

nonmatching NAME_Init, 0x4

dlabel NAME_Init
    /* 004DC774 */ .space 0x04

nonmatching TYPE_Stage_entered, 0x4

dlabel TYPE_Stage_entered
    /* 004DC778 */ .space 0x04

nonmatching jthreadTop, 0x4

dlabel jthreadTop
    /* 004DC77C */ .space 0x04

nonmatching classJava_xeno_Enepc, 0x4

dlabel classJava_xeno_Enepc
    /* 004DC780 */ .space 0x04

nonmatching classVoid, 0x4

dlabel classVoid
    /* 004DC784 */ .space 0x04

nonmatching classJava_xeno_Scene, 0x4

dlabel classJava_xeno_Scene
    /* 004DC788 */ .space 0x04

nonmatching classByte, 0x4

dlabel classByte
    /* 004DC78C */ .space 0x04

nonmatching classJava_xeno_util_Window, 0x4

dlabel classJava_xeno_util_Window
    /* 004DC790 */ .space 0x04

nonmatching classJava_xeno_Uwamono, 0x4

dlabel classJava_xeno_Uwamono
    /* 004DC794 */ .space 0x04

nonmatching classChar, 0x4

dlabel classChar
    /* 004DC798 */ .space 0x04

nonmatching jthreadCurrent, 0x4

dlabel jthreadCurrent
    /* 004DC79C */ .space 0x04

nonmatching classShort, 0x4

dlabel classShort
    /* 004DC7A0 */ .space 0x04

nonmatching classJava_xeno_Chr, 0x4

dlabel classJava_xeno_Chr
    /* 004DC7A4 */ .space 0x04

nonmatching classJava_xeno_util_Format, 0x4

dlabel classJava_xeno_util_Format
    /* 004DC7A8 */ .space 0x04

nonmatching classJava_xeno_Unit, 0x4

dlabel classJava_xeno_Unit
    /* 004DC7AC */ .space 0x04

nonmatching jthreadResetFunc, 0x4

dlabel jthreadResetFunc
    /* 004DC7B0 */ .space 0x04

nonmatching classJava_xeno_vm_System, 0x4

dlabel classJava_xeno_vm_System
    /* 004DC7B4 */ .space 0x04

nonmatching classJava_xeno_util_Vector4f, 0x4

dlabel classJava_xeno_util_Vector4f
    /* 004DC7B8 */ .space 0x04

nonmatching initVMThread, 0x4

dlabel initVMThread
    /* 004DC7BC */ .space 0x04

nonmatching classObject, 0x4

dlabel classObject
    /* 004DC7C0 */ .space 0x04

nonmatching classJava_xeno_util_Runtime, 0x4

dlabel classJava_xeno_util_Runtime
    /* 004DC7C4 */ .space 0x04

nonmatching classEntryPool, 0x4

dlabel classEntryPool
    /* 004DC7C8 */ .space 0x04

nonmatching classJava_xeno_util_Layout, 0x4

dlabel classJava_xeno_util_Layout
    /* 004DC7CC */ .space 0x04

nonmatching classFloat, 0x4

dlabel classFloat
    /* 004DC7D0 */ .space 0x04

nonmatching classJava_xeno_Effect, 0x4

dlabel classJava_xeno_Effect
    /* 004DC7D4 */ .space 0x04

nonmatching classDouble, 0x4

dlabel classDouble
    /* 004DC7D8 */ .space 0x04

nonmatching classLong, 0x4

dlabel classLong
    /* 004DC7DC */ .space 0x04

nonmatching classString, 0x4

dlabel classString
    /* 004DC7E0 */ .space 0x04

nonmatching classJava_xeno_Light, 0x4

dlabel classJava_xeno_Light
    /* 004DC7E4 */ .space 0x04

nonmatching classJava_xeno_util_Menu, 0x4

dlabel classJava_xeno_util_Menu
    /* 004DC7E8 */ .space 0x04

nonmatching classJava_xeno_util_Toolkit, 0x4

dlabel classJava_xeno_util_Toolkit
    /* 004DC7EC */ .space 0x04

nonmatching classJava_xeno_Stage, 0x4

dlabel classJava_xeno_Stage
    /* 004DC7F0 */ .space 0x04

nonmatching classJava_xeno_PlayControl, 0x4

dlabel classJava_xeno_PlayControl
    /* 004DC7F4 */ .space 0x04

nonmatching classJava_xeno_util_TCHParams, 0x4

dlabel classJava_xeno_util_TCHParams
    /* 004DC7F8 */ .space 0x04

nonmatching classJava_xeno_util_Spline, 0x4

dlabel classJava_xeno_util_Spline
    /* 004DC7FC */ .space 0x04

nonmatching classJava_xeno_util_Input, 0x4

dlabel classJava_xeno_util_Input
    /* 004DC800 */ .space 0x04

nonmatching classJava_xeno_Camera, 0x4

dlabel classJava_xeno_Camera
    /* 004DC804 */ .space 0x04

nonmatching classInt, 0x4

dlabel classInt
    /* 004DC808 */ .space 0x04

nonmatching classJava_xeno_Movie, 0x4

dlabel classJava_xeno_Movie
    /* 004DC80C */ .space 0x04

nonmatching errno, 0x70

dlabel errno
    /* 004DC810 */ .space 0x70
