.include "macro.inc"

.section .data, "wa"

/* Generated by spimdisasm 1.40.0 */

nonmatching __EH_FRAME_BEGIN__

dlabel __EH_FRAME_BEGIN__
    /* 2ADE68 004ADE68 00000000 */ .word 0x00000000
    /* 2ADE6C 004ADE6C 00000000 */ .word 0x00000000
enddlabel __EH_FRAME_BEGIN__
