.include "macro.inc"

.section .data, "wa"

/* Generated by spimdisasm 1.40.0 */

nonmatching __CTOR_LIST__

dlabel __CTOR_LIST__
    /* 2ADE54 004ADE54 FFFFFFFF */ .word 0xFFFFFFFF
enddlabel __CTOR_LIST__

nonmatching __CTOR_END__

dlabel __CTOR_END__
    /* 2ADE58 004ADE58 00000000 */ .word 0x00000000
enddlabel __CTOR_END__
