.include "macro.inc"

.section .data, "wa"

/* Generated by spimdisasm 1.40.0 */

nonmatching __DTOR_LIST__

dlabel __DTOR_LIST__
    /* 2ADE5C 004ADE5C FFFFFFFF */ .word 0xFFFFFFFF
enddlabel __DTOR_LIST__

nonmatching __DTOR_END__

dlabel __DTOR_END__
    /* 2ADE60 004ADE60 00000000 */ .word 0x00000000
    /* 2ADE64 004ADE64 00000000 */ .word 0x00000000
enddlabel __DTOR_END__
