#!/usr/bin/env python3
"""Build a decomp-permuter harness for one near-miss function.

    python3 tools/permute_setup.py GetCenter
    python3 tools/permute_setup.py xglMatrixRotV --run

The permuter randomly rewrites the source (reordering statements,
splitting temporaries, changing loop shapes) and keeps whatever scores
closer to the original bytes. It is the right tool for a function whose
C is already SEMANTICALLY correct and only the register allocation or
schedule differs -- the "SCHEDULING" and "REGISTER" triage classes. It
is the wrong tool for a LENGTH diff, where the C shape itself is wrong;
fix that by hand first.

The one thing that makes or breaks a harness is compiling with EXACTLY
the pipeline the real build uses. /opt/permuter/compile_xeno.sh hardcodes
`-O2 -G8` and runs fix_cc_asm.py with no flags, so for any file with a
FILE_CFLAGS_OVERRIDE or FILE_FIX_FLAGS entry it optimizes toward the
wrong target and every "improvement" it reports is measured against the
wrong baseline. This generates a per-function compile.sh from
ccpipe.file_settings(), the same source the build itself reads.

The target object is assembled from the splat asm for that function, so
the bytes being matched against are the original's, with the same
symbolic relocations our own objects carry.
"""
import argparse
import os
import re
import shlex
import subprocess
import sys

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                     ".."))
sys.path.insert(0, os.path.join(ROOT, "tools"))
sys.path.insert(0, ROOT)
PERMUTER = "/opt/permuter"
AS = "/usr/local/ps2dev/ee/bin/mips64r5900el-ps2-elf-as"


def find_source(func):
    """The .c file that defines `func`."""
    pat = re.compile(r'^[A-Za-z_][\w \t\*]*\b%s\s*\(' % re.escape(func), re.M)
    for root, _dirs, files in os.walk(os.path.join(ROOT, "src")):
        for f in sorted(files):
            if f.endswith(".c"):
                p = os.path.join(root, f)
                if pat.search(open(p, errors="ignore").read()):
                    return p
    return None


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("function")
    ap.add_argument("--outdir", default=None)
    ap.add_argument("--run", action="store_true",
                    help="start the permuter immediately after setup")
    ap.add_argument("--threads", "-j", default="4")
    args = ap.parse_args()

    import ccpipe
    from decomplib import Repo

    src = find_source(args.function)
    if not src:
        sys.exit("no source defines %s -- the permuter improves an EXISTING "
                 "C body; write one first (try tools/decompile.py %s)"
                 % (args.function, args.function))
    base = os.path.basename(src)
    cc, cflags, fixflags, asflags = ccpipe.file_settings(base)

    repo = Repo()
    if args.function not in repo.orig_functions:
        sys.exit("%s is not in config/decompiled.txt" % args.function)

    out = args.outdir or os.path.join(ROOT, "permuter", args.function)
    os.makedirs(out, exist_ok=True)

    # --- compile.sh: the real pipeline, flags and all -------------------
    fix = " ".join(shlex.quote(f) for f in fixflags)
    script = f"""#!/usr/bin/env bash
# GENERATED by tools/permute_setup.py for {args.function} ({base}).
# This mirrors ccpipe.file_settings({base!r}) exactly -- if the build's
# flags for this file change, regenerate this harness or the permuter
# will be optimizing toward the wrong target.
set -e
INPUT="$(realpath "$1")"
OUTPUT="$(realpath "$3")"
cd {shlex.quote(ROOT)}
S="$OUTPUT.s"
{shlex.quote(cc)} {cflags} -S -o "$S" "$INPUT"
/opt/venv/bin/python3 tools/fix_cc_asm.py "$S" {fix}
exec {shlex.quote(AS)} {asflags} -o "$OUTPUT" "$S"
"""
    cpath = os.path.join(out, "compile.sh")
    open(cpath, "w").write(script)
    os.chmod(cpath, 0o755)

    # --- target.o: the ORIGINAL bytes, assembled from splat asm ---------
    sys.path.insert(0, os.path.join(ROOT, "tools"))
    import decompile as dec
    path, block = dec.find_function(args.function)
    if not block:
        sys.exit("no splat asm for %s" % args.function)
    tasm = os.path.join(out, "target.s")
    with open(tasm, "w") as fh:
        fh.write(".set noat\n.set noreorder\n\n.section .text, \"ax\"\n\n")
        for l in block:
            if re.match(r'^\s*endlabel\s', l):
                continue
            # `glabel` is a splat macro from asm/macro.inc; gas has never
            # heard of it. Spell it out instead of pulling in the include.
            m = re.match(r'^\s*glabel\s+(\S+)\s*$', l)
            if m:
                fh.write(".globl %s\n%s:\n" % (m.group(1), m.group(1)))
                continue
            fh.write(l)
        fh.write("\n")
    r = subprocess.run([AS] + shlex.split(asflags) + ["-o",
                       os.path.join(out, "target.o"), tasm],
                       capture_output=True, text=True)
    if r.returncode != 0:
        sys.stderr.write(r.stdout + r.stderr)
        sys.exit("could not assemble the original asm for %s" % args.function)

    # --- base.c: preprocessed, with steering forced to no-ops ----------
    # The permuter runs `cpp -P -nostdinc` on base.c and parses the result
    # with pycparser, so base.c must carry no #includes and no inline asm.
    # tools/permuter_matching.h supplies portable macro definitions and
    # pre-trips matching.h's include guard.
    bpath = os.path.join(out, "base.c")
    # NOT ee-gcc: the 2.96 build has no standalone cpp0 (it preprocesses
    # inside cc1), so `-E` fails outright. The host cpp is only used to
    # expand includes for the permuter's parser -- every actual
    # compilation still goes through ee-gcc via compile.sh.
    pre = subprocess.run(
        ["cpp", "-nostdinc", "-I", os.path.join(ROOT, "include"), "-I", ROOT,
         "-include", os.path.join(ROOT, "tools", "permuter_matching.h"),
         src], capture_output=True, text=True, cwd=ROOT)
    if pre.returncode != 0:
        sys.stderr.write(pre.stderr[-1500:])
        sys.exit("could not preprocess %s" % os.path.relpath(src, ROOT))
    body = "\n".join(l for l in pre.stdout.split("\n")
                     if not l.startswith("#"))
    open(bpath, "w").write(body)
    if "__asm__" in body or re.search(r'\basm\s*\(', body):
        print("NOTE: %s still contains raw inline asm after preprocessing.\n"
              "      pycparser cannot parse it, so the permuter will not load\n"
              "      base.c as-is. This is WORKABLE, not fatal -- an agent has\n"
              "      done it: edit %s/base.c and delete the asm-bearing\n"
              "      function bodies that are not the one you are permuting\n"
              "      (PS2_ASM blocks included). The permuter only scores the\n"
              "      function named in settings.toml, so the rest just has to\n"
              "      parse."
              % (os.path.relpath(src, ROOT), os.path.relpath(out, ROOT)))
    # The permuter hunts for mips-linux-gnu-objdump and friends; ours is
    # the EE-specific one, so name it explicitly or setup fails at load.
    open(os.path.join(out, "settings.toml"), "w").write(
        'func_name = "%s"\ncompiler_type = "gcc"\n'
        # objdump_command REPLACES the arguments too, so the mips
        # defaults (-drz -m mips:4300) have to be repeated here.
        'objdump_command = "%s -drz -m mips:4300"\n'
        % (args.function,
           "/usr/local/ps2dev/ee/bin/mips64r5900el-ps2-elf-objdump"))

    rel = os.path.relpath(out, ROOT)
    print("harness: %s" % rel)
    print("  source   %s" % os.path.relpath(src, ROOT))
    print("  cflags   %s" % cflags)
    print("  fixflags %s" % (" ".join(fixflags) or "(none)"))
    run = (f"docker exec -w /work xenosaga-dev bash -c "
           f"'/opt/venv/bin/python3 {PERMUTER}/permuter.py "
           f"-j{args.threads} {rel}'")
    print("\nrun it with:\n  %s" % run)
    print("\nThe permuter prints candidates that score better than the base;\n"
          "score 0 is a match. Copy a winning body back into %s and confirm\n"
          "with tools/checkfile.py before registering." % os.path.relpath(src, ROOT))

    if args.run:
        os.execvp("/opt/venv/bin/python3",
                  ["/opt/venv/bin/python3", PERMUTER + "/permuter.py",
                   "-j" + args.threads, out])
    return 0


if __name__ == "__main__":
    sys.exit(main())
